#!/bin/bash
dim=$1
ps=${dim/.dat/.ps}

TMPDIR=$(mktemp --tmpdir -d WALDIM.XXXXXXXXXX)

if [[ -n $2 ]] ; then
    perfil=$2
else
    perfil=$TMPDIR/perfil.dat
    awk 'BEGIN{n=0;stn=""}{if(NR>1){if(stn!=$1){n++;stn=$1;printf "%2d %s\n",n,stn}}}' $dim > $perfil
fi

awk -v p=$perfil '{
  if(FILENAME==p) {
    pos[$2]=$1
  }
  else {
    if(FNR>1) {
      printf "%s %s %s %s\n",pos[$1],$5,$6,$1
    }
  }
}' $perfil $dim > $TMPDIR/data

X=($(awk '{print $1}' $perfil | sort -g -u |\
 awk '{p[NR]=$1}END{printf "%f %f",p[1]-(p[2]-p[1])/2,p[NR]+(p[NR]-p[NR-1])/2}'))

Y=($(awk '{print $2}' $TMPDIR/data | sort -g -u |\
 awk '{p[NR]=$1}END{printf "%e %e",2*p[1]-sqrt(p[2]*p[1]),2*p[NR]-sqrt(p[NR]*p[NR-1])}'))

psxy $TMPDIR/data -R${X[0]}/${X[1]}/${Y[0]}/${Y[1]} -JX20c/-15cl -Ss10p -Wthinnest -Cwaldim.cpt -Ba1e10/a1pf3nsEW -K > $ps

awk -v T=${Y[0]} '{printf "%s %s 8 90 0 mc %s\n",$1,T,$2}' $perfil |\
pstext -N -R -J -D0c/0.5c -K -O >> $ps

psscale -D21.5/5/-5c/0.5c -L0.1 -Cwaldim.cpt -O --ANNOT_FONT_SIZE_PRIMARY=8p >> $ps

ps2raster -A -P -Tg $ps
eog ${ps/.ps/.png}&
rm -rf $TMPDIR
