      SUBROUTINE G01DAF(N,PP,ETOL,ERREST,WORK,IW,IFAIL)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     G01DAF COMPUTES A SET OF NORMAL SCORES OF SIZE N
C     PARAMETERS -
C     N         THE NUMBER OF NORMAL SCORES TO BE COMPUTED
C     PP        THE SCORES OBTAINED ARE STORED IN PP(1) TO PP(N)
C     ETOL      AN ATTEMPT IS MADE TO COMPUTE THE SCORES WITH
C     AN ESTIMATED ACCURACY OF ETOL OR BETTER
C     FOR EXAMPLE ETOL MAY BE GIVEN THE VALUE 0.000001
C     ERREST    THE COMPUTED ESTIMATE OF THE MAXIMUM ERROR
C     WORK      WORK ARRAY OF DIMENSION  IW ( AT LEAST 3*N/2 )
C     IW        THE DIMENSION OF WORK
C     IFAIL     GIVEN THE FOLLOWING VALUES
C     0       SUCCESS
C     1       IF N IS LESS THAN  1
C     2       IF ETOL IS LESS THAN OR EQUAL TO ZERO
C     3       IF THE ACCURACY REQUESTED THROUGH ETOL
C     COULD NOT BE OBTAINED, PP AND ERREST
C     REFER TO THE BEST SOLUTION OBTAINED
C     4       IF THE VALUE OF IW IS TOO SMALL
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='G01DAF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  ERREST, ETOL
      INTEGER           IFAIL, IW, N
C     .. Array Arguments ..
      DOUBLE PRECISION  PP(N), WORK(IW)
C     .. Local Scalars ..
      INTEGER           IW2, IW3, JFAIL, NDIV2
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          G01DAZ
C     .. Executable Statements ..
      NDIV2 = N/2
      JFAIL = 4
      IF (3*NDIV2.GT.IW) GO TO 20
      IW2 = 1 + NDIV2
      IW3 = IW2 + NDIV2
      JFAIL = IFAIL
      CALL G01DAZ(N,NDIV2,WORK,WORK(IW2),WORK(IW3),PP,ETOL,ERREST,JFAIL)
      IF (JFAIL.NE.0) GO TO 20
      IFAIL = 0
      RETURN
   20 IFAIL = P01ABF(IFAIL,JFAIL,SRNAME,0,P01REC)
      RETURN
      END
