      SUBROUTINE G02BNZ(A,N,NV,IP,IST)
C     MARK 4 RELEASE NAG COPYRIGHT 1974.
C     MARK 4.5 REVISED
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     NAG AUXILIARY SUBROUTINE G02BNZ
C     WRITTEN 23. 7.73 BY PAUL GRIFFITHS (OXFORD UNIVERSITY)
C
C     COMPLETELY COPIED FROM M01AAF BUT OMITTING INITIALIZATION OF
C     IP AND IST AND FINAL SHIFT OF IP.
C     ROUTINE IS USED TO ORDER OBSERVATIONS FOR THE RANK
C     CORRELATION
C     ROUTINES -- NAMELY G02BNF,G02BPF,G02BQF,G02BRF,G02BSF
C
C     ARRAY A CONTAINS THE ACTUAL OBSERVATIONS
C     N IS THE TOTAL NUMBER OF OBSERVATIONS
C     NV IS THE NUMBER OF VALID OBSERVATIONS
C     ON INPUT IP(I) IS EQUAL TO I IF OBSERVATION I IS TO BE
C     INCLUDED IN CALCULATIONS, AND ZERO OTHERWISE
C     IST(I) CONTAINS POINTER TO NEXT HIGHEST OBSERVATION,
C     ON OUTPUT IP(I) CONTAINS POINTER TO NEXT HIGHEST OBSERVATION
C     (EXCEPT FOR THE LARGEST OBSERVATION WHICH
C     POINTS TO ITSELF)
C     IST(1) IS POINTER TO SMALLEST OBSERVATION
C
C     .. Scalar Arguments ..
      INTEGER           N, NV
C     .. Array Arguments ..
      DOUBLE PRECISION  A(N)
      INTEGER           IP(N), IST(N)
C     .. Local Scalars ..
      INTEGER           I, J, JS, K, L, LIMIT, NEWLOW, NL
C     .. Executable Statements ..
      NL = NV
   20 LIMIT = NL/2
      JS = -1
      L = 0
   40 L = L + 1
      JS = JS + 2
      I = IST(JS)
      J = IST(JS+1)
   60 IF (A(I).GT.A(J)) GO TO 80
      NEWLOW = I
      I = IP(I)
      GO TO 100
   80 NEWLOW = J
      J = IP(J)
  100 K = NEWLOW
  120 IF (A(I).GT.A(J)) GO TO 140
      IP(K) = I
      K = I
      I = IP(I)
      IF (IP(K)-K) 120, 180, 120
  140 IP(K) = J
      K = J
      J = IP(J)
      IF (IP(K)-K) 120, 160, 120
  160 J = I
  180 IP(K) = J
      K = J
      IF (IP(J)-J) 200, 220, 200
  200 J = IP(J)
      GO TO 180
  220 IST(L) = NEWLOW
      IF (L.LT.LIMIT) GO TO 40
      IF (JS+1-NL) 240, 260, 260
  240 JS = JS + 2
      I = IST(L)
      J = IST(JS)
      GO TO 60
  260 NL = LIMIT
      IF (LIMIT.GT.1) GO TO 20
      RETURN
      END
