      SUBROUTINE G13BFW(H,IDH,I,J,KSGN,NUM,F,KFL,MSN,NMS,IX,JX)
C     MARK 11 RELEASE. NAG COPYRIGHT 1983.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     SUBROUTINE G13BFW DERIVES F, AN ELEMENT OF THE INVERSE
C     OF MATRIX H. F IS EQUIVALENT TO M(I,J) IN THE
C     ALGORITHM USED TO CONSTRUCT A VECTOR OF CORRECTIONS
C     TO THE TERMS OF THE DERIVATIVE VECTOR ASSOCIATED
C     WITH THE ARIMA PARAMETERS
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION  F
      INTEGER           I, IDH, IX, J, JX, KFL, KSGN, NMS, NUM
C     .. Array Arguments ..
      DOUBLE PRECISION  H(IDH,NUM)
      INTEGER           MSN(NMS)
C     .. Executable Statements ..
      KFL = 1
      IX = I + 1
      JX = J
      IF (I.GE.J) GO TO 20
      IX = J + 1
      JX = I
   20 F = H(IX,JX)
      IF ((MSN(I+1)*MSN(J+1)*KSGN).GE.0) GO TO 40
      KFL = -1
      F = -F
   40 RETURN
      END
