      SUBROUTINE G13CGF(XG,YG,XYRG,XYIG,NG,STATS,L,N,ER,ERLW,ERUP,RF,
     *                  RFSE,IFAIL)
C     MARK 10 RELEASE. NAG COPYRIGHT 1982.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     FOR A BIVARIATE TIME SERIES, G13CGF CALCULATES THE
C     NOISE SPECTRUM  TOGETHER WITH MULTIPLYING FACTORS
C     FOR THE BOUNDS AND THE IMPULSE RESPONSE FUNCTION
C     AND ITS STANDARD ERROR, FROM THE UNIVARIATE
C     AND BIVARIATE SPECTRA.
C
C     CONTRIBUTORS - G. TUNNICLIFFE WILSON,M. HURLEY (LANC. UNIV.)
C     VALIDATOR    - T. LAMBERT ( NAG CENTRAL OFFICE )
C
C     USES NAG LIBRARY ROUTINES G13CGZ, P01AAF
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='G13CGF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  ERLW, ERUP, RFSE
      INTEGER           IFAIL, L, N, NG
C     .. Array Arguments ..
      DOUBLE PRECISION  ER(NG), RF(L), STATS(4), XG(NG), XYIG(NG),
     *                  XYRG(NG), YG(NG)
C     .. Local Scalars ..
      INTEGER           IERROR, M
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          G13CGZ
C     .. Executable Statements ..
      IERROR = 1
C     CHECK NOISE ARRAY DIMENSION
      IF (NG.LT.1) GO TO 20
C     CHECK STATS ARRAY
      IF (STATS(1).LT.3.0D0) GO TO 20
      IF (STATS(2).LE.0.0D0 .OR. STATS(2).GT.1.0D0) GO TO 20
      IF (STATS(3).LT.1.0D0) GO TO 20
C     CHECK DATA SET SIZE
      IF (N.LE.0) GO TO 20
C     CHECK RELATIONSHIP BETWEEN L AND NG
      IERROR = 6
      M = L/2 + 1
      IF (NG.NE.M) GO TO 20
      IERROR = 0
      CALL G13CGZ(XG,YG,XYRG,XYIG,NG,STATS,L,N,ER,ERLW,ERUP,RF,RFSE,
     *            IERROR)
      IF (IERROR.NE.0) GO TO 20
C
C     SUCCESSFUL EXIT
      IFAIL = 0
      RETURN
C
C     COME HERE IF ERRORS
   20 IFAIL = P01ABF(IFAIL,IERROR,SRNAME,0,P01REC)
      RETURN
      END
