      SUBROUTINE G13CBF(NX,MTX,PX,MW,PW,L,KC,LG,XG,NG,STATS,IFAIL)
C     MARK 10 RELEASE. NAG COPYRIGHT 1982.
C     MARK 10B REVISED. IER-405 (JAN 1983).
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     G13CBF CALCULATES THE SMOOTHED SAMPLE SPECTRUM OF A
C     UNIVARIATE TIME SERIES USING SPECTRAL SMOOTHING BY
C     THE TRAPEZIUM FREQUENCY (DANIELL) WINDOW.
C
C     CONTRIBUTORS - G. TUNNICLIFFE WILSON,M. HURLEY (LANC. UNIV.)
C     VALIDATOR    - T. LAMBERT ( NAG CENTRAL OFFICE )
C
C     USES NAG LIBRARY ROUTINES G13CAZ, P01AAF
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='G13CBF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  PW, PX
      INTEGER           IFAIL, KC, L, LG, MTX, MW, NG, NX
C     .. Array Arguments ..
      DOUBLE PRECISION  STATS(4), XG(KC)
C     .. Local Scalars ..
      INTEGER           IERROR
C     .. Local Arrays ..
      DOUBLE PRECISION  C(1)
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          G13CAZ
C     .. Intrinsic Functions ..
      INTRINSIC         MOD
C     .. Executable Statements ..
      IERROR = 1
C
C     CHECK THE DATA SET SIZE NON ZERO
      IF (NX.LT.1) GO TO 40
C     CHECK MEAN-TREND CORRECTION INDICATOR
      IF (MTX.LT.0 .OR. MTX.GT.2) GO TO 40
C     CHECK THE DATA WINDOW PROPORTION
      IF (PX.LT.0.0D0 .OR. PX.GT.1.0D0) GO TO 40
C     CHECK FREQUENCY WIDTH OF SMOOTHING WINDOW
      IF (MW.EQ.NX) GO TO 20
      IF (MW.LT.1 .OR. MW.GT.NX) GO TO 40
C     CHECK WINDOW SHAPE PROPORTION
      IF (PW.LT.0.0D0 .OR. PW.GT.1.0D0) GO TO 40
C     CHECK FREQ OF DIVISION OF SMOOTHED SPECTRUM ESTS
   20 IF (L.LT.1) GO TO 40
C
C     CHECK ORDER OF TRANSFORM
      IERROR = 2
      IF (KC.LT.(2*NX) .OR. MOD(KC,L).NE.0) GO TO 40
C
C
C     IF THIS POINT IS REACHED USER SUPPLIED
C     PARAMETERS HAVE PASSED INITIAL CHECKS
      IF (MW.LT.NX) C(1) = PW
      IERROR = 0
      CALL G13CAZ(NX,MTX,PX,5,MW,0,1,C,KC,L,LG,KC,XG,NG,STATS,IERROR)
      IF (IERROR.NE.0) GO TO 40
C
C     SUCCESSFUL EXIT
      IFAIL = 0
      RETURN
C
C     COME HERE IF ERRORS
   40 IFAIL = P01ABF(IFAIL,IERROR,SRNAME,0,P01REC)
      RETURN
      END
