function [h_pwdialog] = pwdialog(Pwhd);

%  Usage : [h_pwdialog] = pwdialog(Pwhd);

%  channels chosen for plotting, rotation are global variables
%  ref_ch  =  reference channels (currently has to be an actual channel #)
%  rot_ch  =  channel numbers for rotation pairs
%  sing_ch =  channel numbers for single (unpaired for rotation) channels 
%  plot_ch =  channels to plot TFs for
%  theta_rot = rotation angle
global ref_ch sing_ch rot_ch plot_ch theta_rot poluse chplot

%  all of these are associated with dialogue box which controls
%  channel rotations etc.
global chnum chuse chname chhand name_list nlines plt_type

pwstmon;
%  some parameters

%  Set up default channel pairings, etc 

ref_ch = [];
rot_ch = [];
sing_ch = [];
plot_ch = [];
theta_rot = 0.;
poluse = 1;
[nchid,nt] = size(Pwhd.chid);

for ista = 1:Pwhd.nsta
%  for each station check to see if first two channels are Hx Hy
   i1 = Pwhd.ih(ista); i2 = i1 + 1;
   nch = Pwhd.nch(ista);
   if( upper(setstr([ Pwhd.chid(1:2,i1)' Pwhd.chid(1:2,i2)'])) == 'HXHY'  | ...
      upper(setstr([ Pwhd.chid(1:2,i1)' Pwhd.chid(1:2,i2)'])) == 'HYHX' ) 
     rot_ch = [ rot_ch ; [i1 i2 ] ];
     if( length(ref_ch ) == 0 )
        ref_ch = [i1 ; i2 ];
     end
     nche = nch - 2;
     chid = setstr(Pwhd.chid(:,i1:i1+nch-1)');
   else
     nche = nch;
     chid = zeros(nch+2,nchid);
     chid(3:nch+2,:)  = setstr(Pwhd.chid(:,i1:i1+nch-1)');
   end
   [xy,yx,hz,xypairs,DipoleSetup] = ecomp(nche,chid);
   temp = xypairs' + Pwhd.ih(ista) + nch - nche - 1;
   rot_ch = [ rot_ch ; temp ];
   temp = hz + Pwhd.ih(ista) +nch - nche - 1;
   sing_ch = [ sing_ch temp ];
end

%  make sure reference channels are at the beginning of the
%  rotation pair indices list
ind = rot_ch(:,1) ~= ref_ch(1);
rot_ch = [ ref_ch' ; rot_ch(ind,:)];

nrot = length(rot_ch(:,1));
nsing = length(sing_ch);

nlines = 2*nrot+nsing;


height = (nlines + nextra)*height_1;
paper_fac = 70;
rect_fig = [ loc width height ];
h_pwdialog = figure('Position',rect_fig,...
	'MenuBar','None',...
	'NumberTitle','Off',...
	'PaperPosition',[1,2,width/paper_fac,height/paper_fac],...
	'Name','General Multi-station Transfer Function Plots : Pw-files');

name_list = Pwhd.ch_name;
nm = size(name_list) ;
nchar = nm(2);
name_list = [ name_list ; blanks(nchar) ];
chname = zeros(2,nlines,nchar);
chnum = zeros(2,nlines);

%  positions for channel name windows
dhn = 1/(nlines+nextra);
pos(1,1,:) = [ .05  1-2.5*dhn .35 dhn/1.1 ] ; 
chname(1,1,:) = blanks(nchar);
for k = 2:nlines
  pos(1,k,:) = [ .05 1-(k+3.5)*dhn .35 dhn/1.1 ];
  chname(1,k,:) = blanks(nchar);
end
pos(2,:,:) = pos(1,:,:);
pos(2,:,1) = pos(1,:,1) + .5;
chname(2,:,:) = chname(1,:,:);
chuse = zeros(2,nlines);
chhand = zeros(2,2,nlines);

%  positions for number edit boxes
pos_edit = pos;
pos_edit(:,:,3) = .075;
pos_edit(1,:,1) = .4;
pos_edit(2,:,1) = .9;

% default paired channels
chnum(:,1:nrot) = rot_ch';
chname(1,1:nrot,:) = name_list(rot_ch(:,1),:);
chname(2,1:nrot,:) = name_list(rot_ch(:,2),:);

% default single channels
i1 = nrot+1
i2 = nrot+nsing;
chnum(1,i1:i2) = sing_ch;
chname(1,i1:i2,:) = name_list(sing_ch,:);

uicontrol('Style','text',...
   'parent',h_pwdialog, ...
   'String','Reference Channels: Check Left Box For Hx Polarization, Right for Hy',...
   'Units','normalized',...
   'Position',[0.05 1-dhn*1.5 .90 dhn],...
   'HorizontalAlignment','Center');

chhand(1,1,1) = uicontrol('style','checkbox', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos(1,1,:), ...
	'UserData',[1,1], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',setstr(chname(1,1,:)), ...
	'callback','chuseset');
		    
chhand(1,2,1) = uicontrol('style','checkbox', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos(2,1,:), ...
	'UserData',[2,1], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',setstr(chname(2,1,:)), ...
	'callback','chuseset');
		    
chhand(2,1,1) = uicontrol('style','edit', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos_edit(1,1,:), ...
	'UserData',[1,1], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',numstrbl(chnum(1,1)), ...
	'callback','chchng');
		    
chhand(2,2,1) = uicontrol('style','edit', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos_edit(2,1,:), ...
	'UserData',[2,1], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',numstrbl(chnum(2,1)), ...
	'callback','chchng');

set(chhand(1,poluse,1),'Value',1);
%   Now predicted channels ...
uicontrol('Style','text',...
   'parent',h_pwdialog, ...
   'String','Predicted Channels: Check box to pick rotated components for plotting;',...
   'Units','normalized',...
   'Position',[0.05 1-dhn*3.75 .90 dhn],...
   'HorizontalAlignment','Center');
uicontrol('Style','text',...
   'parent',h_pwdialog, ...
   'String','Edit number fields to change channel pairings for rotation/reference',...
   'Units','normalized',...
   'Position',[0.05 1-dhn*4.6 .90 dhn],...
   'HorizontalAlignment','Center');


%
for k = 2:nlines
   chhand(1,1,k) = uicontrol('style','checkbox', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos(1,k,:), ...
	'UserData',[1,k], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',setstr(chname(1,k,:)), ...
	'callback','chuseset');
		    
   chhand(1,2,k) = uicontrol('style','checkbox', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos(2,k,:), ...
	'UserData',[2,k], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',setstr(chname(2,k,:)), ...
	'callback','chuseset');
		    
   chhand(2,1,k) = uicontrol('style','edit', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos_edit(1,k,:), ...
	'UserData',[1,k], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string',numstrbl(chnum(1,k)), ...
	'callback','chchng');
		    
   chhand(2,2,k) = uicontrol('style','edit', ...
	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',pos_edit(2,k,:), ...
	'UserData',[2,k], ...
	'FontWeight','bold', ...
	'Fontsize',fs_chname, ...
	'string',numstrbl(chnum(2,k)), ...
	'callback','chchng');
end

%   save defaults...

chnum_d = chnum;
chname_d = chname;

%   buttons for plotting, ...

h_plot = uicontrol('style','pushbutton', ...
  	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',[.05,dhn*.5,.2,dhn], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string','Plot', ...
	'callback','new_plot; ', ...
	'HorizontalAlignment','Center');

%h_plot = uicontrol('style','pushbutton', ...
%	'parent',h_pwdialog, ...
%	'units','normalized', ...
%	'position',[.28,dhn*.5,.2,dhn], ...
%	'Fontsize',fs_chname, ...
%	'FontWeight','bold', ...
%	'string','Defaults', ...
%	'callback','defreset', ...
%	'HorizontalAlignment','Center');

h_plot = uicontrol('style','pushbutton', ...
  	'parent',h_pwdialog, ...
	'units','normalized', ...
	'position',[.51,dhn*.5,.2,dhn], ...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string','Add TF', ...
	'callback','add_tf', ...
	'HorizontalAlignment','Center');

h_plot = uicontrol('style','pushbutton', ...
  	'parent',h_pwdialog, ...
	'units','normalized', ...
   'position',[.73,dhn*.5,.2,dhn], ...
   'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'string','Quit', ...
	'callback','pw_quit', ...
	'HorizontalAlignment','Center');

uicontrol('Style','text',...
	'parent',h_pwdialog, ...
	'String','Rotation Angle',...
	'Units','normalized',...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'Position',[0.05 2.15*dhn .25 dhn],...
	'HorizontalAlignment','Center');
	
uicontrol('Style','edit',...
	'parent',h_pwdialog, ...
	'String',num2str(theta_rot),...
	'Units','normalized',...
	'FontWeight','bold', ...
	'Fontsize',fs_chname, ...
	'Position',[0.325,2.15*dhn,.15,dhn],...
   'Callback','theta_rot=str2num(get(gco,''String''));');

uicontrol('Style','popupmenu',...
	'parent',h_pwdialog, ...
	'String','Amp/Phase | Log Amp/Phase | Real/Imag',...
	'Units','normalized',...
	'Fontsize',fs_chname, ...
	'FontWeight','bold', ...
	'Position',[0.55 2.15*dhn .40 dhn],...
   'HorizontalAlignment','Center',...
   'Callback','k = get(gco,''Value'');plt_type=ptyps(k,:);');

