      integer IN,  OUT
      integer IND1,  IND2,  IND3,  IND4
      integer OUTD1, OUTD2, OUTD3, OUTD4

      parameter (
     &            IN  =   5,
     &            OUT  =  6,
     &            IND1 =  4,
     &            IND2 =  3,
     &            IND3 =  2,
     &            IND4 =  1,
     &            OUTD1 = 7,
     &            OUTD2 = 8,
     &            OUTD3 = 9,
     &            OUTD4 = 10
     &          )
      


