#!/bin/bash

progName=$(basename $0)
if [[ $# != 1 ]] ; then
    echo "uso: $progName arquivo-lemi.t*"
    exit 1
fi

ESCALA=100
arquivo=$1
if [[ ! -f "$arquivo" ]] ; then
    echo "arquivo \"$arquivo\" não encontrado"
    exit 1
fi

ID=$(basename $arquivo)
arq_ascA=${ID%.t*}
arq_ascA=$arq_ascA"A.asc"
arq_ascB=${arq_ascA/A.asc/B.asc}
arq_clkA=${arq_ascA/A.asc/A.clk}
arq_clkB=${arq_ascA/A.asc/B.clk}
arq_spA=${arq_ascA/A.asc/A.sp}
arq_spB=${arq_ascA/A.asc/B.sp}

if [[ ! -a $PWD/paths.cfg ]]
then
    echo "não encontrou o arquivo paths.cfg do EMTF. Diretório correto?"
    exit 1
fi

DIR_DATA=$(awk '{if(NR==1)print $1}' paths.cfg)
DIR_SP=$(awk '{if(NR==2)print $1}' paths.cfg)

if [[ ! -d $PWD/$DIR_DATA ]]
then
    echo "não encontrou o diretório $DIR_DATA do EMTF."
    exit 1
fi

if [[ ! -d $PWD/$DIR_SP ]]
then
    echo "não encontrou o diretório $DIR_SP do EMTF."
    exit 1
fi

TAXA=$(awk '{if(NR<=2){printf "%s-%s-%sT%s:%s:%s\n",$1,$2,$3,$4,$5,$6}}' $arquivo | gmtconvert -fi0T -fo0t --TIME_SYSTEM=UNIX | awk '{if(NR==1){to=$1}else{print $1-to}}')
awk -v t=$TAXA '{if(NR==1){printf "%s\n %s %s %s %s %s %02.0f\n %s 01 01 00 00 00\n",t,substr($1,3),$2,$3,$4,$5,$6,substr($1,3)}}' $arquivo > $PWD/$DIR_DATA/$arq_clkA
cp $PWD/$DIR_DATA/$arq_clkA $PWD/$DIR_DATA/$arq_clkB

awk -v a=$ID -v t=$TAXA -v s=$ESCALA 'BEGIN{printf "%s\n0.00 0.00\n0.00\n5\n%s\n0. 0.\nHx\n0 0.\n%f 0\nHy\n90 0.\n%f 0\nHz\n0 0.\n%f 0\nEx\n1.0 0.0 0. 1.\n%f 0\nEy\n1.0 90.0 0. 1\n%f 0\n",a,t,1/s,1/s,1/s,1/s,1/s}'> $PWD/$DIR_SP/$arq_spA
cp $PWD/$DIR_SP/$arq_spA $PWD/$DIR_SP/$arq_spB
awk -v s=$ESCALA '{printf "%.0f %.0f %.0f %.0f %.0f\n",$7*s,$8*s,$9*s,$12*s,$13*s}' $arquivo > $PWD/$DIR_DATA/$arq_ascA
awk -v s=$ESCALA '{printf "%.0f %.0f %.0f %.0f %.0f\n",$7*s,$8*s,$9*s,$14*s,$15*s}' $arquivo > $PWD/$DIR_DATA/$arq_ascB
