#!/bin/bash
if [[ $# -eq 0 ]] ;then
    echo "usage: $0 lemi.tNN ..."
    echo "where lemi.tNN is an asc lemi file"
    echo
    echo "for each input file there is an output line:"
    echo "file-name start-unix-time end-unix-time sampling-period..."
    echo
    echo "abnormal files will have more than one sampling-period"
    echo
    exit 1
fi

while [[ -n $1 ]] ; do
    awk '{printf "%d-%02d-%02dT%02d:%02d:%05.2f\n",$1,$2,$3,$4,$5,$6}' $1 |\
    gmtconvert -fi0T -fo0t --TIME_SYSTEM=UNIX |\
    awk -v n=$1 '{
                   if(NR==1) {
                     ti=$1
                   }
                   else {
                     a[$1-t]
                   }
                   t=$1
                 }
                 END{
                   printf "%s %s %s",n,ti,t
                   for (val in a) {
                     printf " %s",val
                   }
                   printf "\n"
                 }'
    shift
done
