#!/bin/bash
if [[ $# -ne 1 ]] ;then
    echo "usage: $0 check-time.log"
    echo "where check-time.log is the output from lemi-check-time"
    echo
    echo "for each continuous measurement there is an output line:"
    echo "start-unix-time end-unix-time sampling-period lemi-asc-file..."
    echo
    echo "abnormal files will be skipped"
    echo
    exit 1
fi

input=$1
# skip any file with more than one sampling periods and sort by stat time
awk '{if(NF==4)print $0}' $input | sort -g -k 2 |\
awk '{
       n[NR]=$1 # file name
       b[NR]=$2 # begin
       e[NR]=$3 # end
       s[NR]=$4 # sampling period
     }
     END{
       while(length(n)>0) {
         bg=0
         for (i=1;i<=NR;i++) {
           if (i in n) { # if not deleted
             if(bg==0){ # new group
               g=n[i]
               bg=b[i]
               eg=e[i]
               sg=s[i]
               delete n[i]
             }
             else {
               if(sg==s[i]&&b[i]==(eg+sg)) { # same group
                 g=sprintf("%s %s",g,n[i])
                 eg=e[i]
                 delete n[i]
               }
             }
           }
         }
         printf "%s %s %s %s\n",bg,eg,sg,g
       }
     }'
