#!/bin/bash
# make a string to inicialize an associative array with current GMT defaults
# useful to check gmt_defaults
gmt_defaults=$(gmtdefaults -L | awk '{
  if(substr($1,1,1)!="#") {
    printf " [%s]=\"",$1
    for(c=3;c<=NF;c++) {
      printf "%s",$c
      if(c!=NF) {
        printf " "
      }
    }
    printf "\""
  }
}')

echo "declare -A gmt_defaults"
echo "gmt_defaults=($gmt_defaults)"
