#!/bin/bash
if [[ $# != 1 ]] ; then
    echo "usage: $(basename $0) file.dcmp"
    exit 1
fi
DCMP=$1

# remove extension .dcmp
ID=${DCMP/.dcmp/}
if [[ "$ID.dcmp" != $DCMP ]]
then
    echo "expected a file *.dcmp"
    exit 1
fi
IMPED=imped${ID:3}.dat
if [[ !(-e $DCMP) ]]
then
    echo "couldn't find $DCMP"
    exit 1
fi
if [[ !(-e $IMPED) ]]
then
    echo "couldn't find $IMPED"
    exit 1
fi
ps=${ID}.ps
TITLE=$ID
TMIN=1e-4
TMAX=1e3

export GMT_TMPDIR=$(mktemp -d /tmp/gmt.XXXXXX)

gmtset ANOT_FONT_SIZE 8p LABEL_FONT_SIZE 10p ANNOT_OFFSET_PRIMARY 0.1c PAPER_MEDIA a4

# title
echo "6.1 0.5 16 0 0 MC $TITLE" |\
pstext -X4.3c -Y26.8c -R0/12.2/0/1 -Jx1 -K -P > $ps

# plot error CHI^2

psbasemap -Y-4.8c -JX5.6cl/4.8cl -R$TMIN/$TMAX/1e-2/1e4 -Ba1p/a1p:"Error":Wsne -K -O >> $ps

dcmp2gmt -I$DCMP -Derr -Q | \
psxy -JX -R -Sc0.15 -EY0p/0.25p/0 -G0 -W0.25p/0 -K -O >> $ps

psxy -JX -R -W0.8p -K -O <<end>> $ps
$TMIN 4
$TMAX 4
end

# plot rho XY and YX

psbasemap -X6.6c -JX5.6cl/4.8cl -R$TMIN/$TMAX/1e-1/1e5 -Ba1p/a1p:"Rho Apparent (Ohm-m)":wsnE -K -O >> $ps

dcmp2gmt -I$DCMP -Drhoa -Q | \
psxy -JX -R -Ss5p -EY0p/0.25p/0 -G0 -K -O >> $ps

dcmp2gmt -I$DCMP -Drhob -Q | \
psxy -JX -R -St5p -EY0p/0.25p/100 -G100 -K -O >> $ps

# plot phase XY and YX (360o=>5.4575 decades)

psbasemap -Y-3.2c -JX5.6cl/2.2c -R$TMIN/$TMAX/-45/135 -Ba1p:"Period (s)":/a45f15:"@~f@~ (deg)":wsnE -K -O >> $ps

# trace 0 and 90 degrees boundaries
psxy $M -JX -R -W0.5p/128 -K -O <<EOF>> $ps
>
$TMIN  0
$TMAX  0
>
$TMIN 90
$TMAX 90
EOF

dcmp2gmt -I$DCMP -Dphia -Q | \
psxy -JX -R -Ss5p -EY0p/0.25p/0 -G0 -K -O >> $ps

dcmp2gmt -I$DCMP -Dphib -Q | \
psxy -JX -R -St5p -EY0p/0.25p/100 -G100 -K -O >> $ps

# PHASE DIFF (360o=>5.4575 decades)

psbasemap -Y-2.2c -JX5.6cl/2.2c -R$TMIN/$TMAX/-45/45 -Ba1p:"Period (s)":/a15f5g90:"@~f@~@-dif@-(deg)":wSnE -K -O >> $ps

dcmp2gmt -I$DCMP -Dphidif -Q | \
psxy -JX -R -Ss5p -EY0p/0.25p/0 -G0 -K -O >> $ps

# STRIKE CURRENT SHEAR TWIST

psbasemap -X-6.6c -JX5.6cl/4.4c -R$TMIN/$TMAX/0/60 -Ba1p/a10f2snE -K -O >> $ps

dcmp2gmt -I$DCMP -Dsh -Q |\
awk '{if($2<0){print $1,-1*$2,-1*$3,-1*$4,-1*$5,-1*$6}}' |\
psxy -JX -R -S+4p -EY0p/0.25p/0 -Gred -Wthin,red -K -O >> $ps
dcmp2gmt -I$DCMP -Dsh -Q | awk '{if($2>=0){print $0}}' |\
psxy -JX -R -S+4p -EY0p/0.25p/0 -Gblue -Wthin,blue -K -O >> $ps

dcmp2gmt -I$DCMP -Dtw -Q |\
awk '{if($2<0){print $1,-1*$2,-1*$3,-1*$4,-1*$5,-1*$6}}' |\
psxy -JX -R -Sx4p -EY0p/0.25p/0 -Gred -Wthin,red -K -O >> $ps
dcmp2gmt -I$DCMP -Dtw -Q | awk '{if($2>=0){print $0}}' |\
psxy -JX -R -Sx4p -EY0p/0.25p/0 -Gblue -Wthin,blue -K -O >> $ps

psbasemap -J -R$TMIN/$TMAX/-90/90 -Ba1p:"Period (s)":/a30f10:"Azimuthal Parameters (deg)":WSn -K -O >> $ps

dcmp2gmt -I$DCMP -Dazim -Q | \
psxy -JX -R -Sd4p -EY0p/0.25p/0 -G0 -K -O >> $ps

dcmp2gmt -I$DCMP -Dch -Q | \
psxy -JX -R -Sc4p -EY0p/0.25p/0 -W0p/0 -K -O >> $ps

dcmp2gmt -I$DCMP -Dtw -Q |\
awk '{if(NR%2==1)printf "%s 95 6 90 0 MC %d\n",$1,NR}' |\
pstext -N -JX -R -G60 -K -O >> $ps
dcmp2gmt -I$DCMP -Dtw -Q |\
awk '{if(NR%2==1)printf "%s -95 6 90 0 MC %d\n",$1,NR}' |\
pstext -N -JX -R -G60 -K -O >> $ps

# Legends
# STRIKE CURRENT SHEAR TWIST
echo "0.4 0.5" | psxy -Y4.4 -R0/12.2/0/1 -Jx1 -Sd4p -G0 -K -O >> $ps
echo "0.4 0.5 8 0 0 ML strike" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "2.0 0.5" | psxy -R -Jx -Sc4p -W0p/0 -K -O >> $ps
echo "2.0 0.5 8 0 0 ML current" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "3.6 0.5" | psxy -R -Jx -S+4p -G0 -K -O >> $ps
echo "3.6 0.5 8 0 0 ML shear" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "5.2 0.5" | psxy -R -Jx -Sx4p -G0 -K -O >> $ps
echo "5.2 0.5 8 0 0 ML twist" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

# XY e YX (resist)
echo "8.6 0.5" | psxy -R -Jx -Ss5p -G0 -K -O >> $ps
echo "8.6 0.5 8 0 0 ML XY" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "10.2 0.5" | psxy -R -Jx -St5p -G100 -K -O >> $ps
echo "10.2 0.5 8 0 0 ML YX" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

# Plot impedances
#
# look for a integer multiple of 10 for maximum variation;
# force minmax be in this range.

components=(xx xy yx yy)
# find maximum difference for each component
MAX_VAR_Z=0
for (( j=0; j < ${#components[*]}; j++ ))
do
    imped2gmt -I$IMPED -D${components[$j]} -S |\
    awk '{printf "%s\n%s\n",$2,$3}' > $GMT_TMPDIR/Z
    MIN_Z[$j]=$(minmax $GMT_TMPDIR/Z -C |awk '{print $1}')
    MAX_Z[$j]=$(minmax $GMT_TMPDIR/Z -C |awk '{print $2}')
    MAX_VAR_Z=$(echo ${MIN_Z[$j]} ${MAX_Z[$j]} |\
            awk -v max=$MAX_VAR_Z '{a=$2-$1;if(a>max){print a}else{print max}}')
    rm $GMT_TMPDIR/Z
done
ANOTY=$(echo $MAX_VAR_Z | awk '{printf "%.0f",$1/10+0.5}')
MAX_VAR_Z=$(echo "10*$ANOTY" | bc -l)
XX=0
XY=1
YX=2
YY=3
for (( j=0; j < ${#components[*]}; j++ ))
do
    MIN_Z[$j]=$(echo ${MIN_Z[$j]} $ANOTY | awk '{printf "%.0f",int($1/$2)*$2}')
    MAX_Z[$j]=$(echo ${MAX_Z[$j]} $ANOTY | awk '{printf "%.0f",int($1/$2)*$2}')
    VAR_Z=$(echo ${MIN_Z[$j]} ${MAX_Z[$j]} | awk '{printf "%.0f",$2-$1}')
    while (( $VAR_Z != $MAX_VAR_Z ))
    do
        MIN_Z[$j]=$(echo "${MIN_Z[$j]}-$ANOTY" | bc -l)
        VAR_Z=$(echo ${MIN_Z[$j]} ${MAX_Z[$j]} | awk '{printf "%.0f",$2-$1}')
        if (( $VAR_Z == $MAX_VAR_Z ))
        then
            break
        fi
        MAX_Z[$j]=$(echo "${MAX_Z[$j]}+$ANOTY" | bc -l)
        VAR_Z=$(echo ${MIN_Z[$j]} ${MAX_Z[$j]} | awk '{printf "%.0f",$2-$1}')
    done
done

# ZXX
psbasemap -Y-12.2c -JX5.6cl/4.8c -R$TMIN/$TMAX/${MIN_Z[$XX]}/${MAX_Z[$XX]} -Ba1p/a${ANOTY}:"Zxx":Wsne -K -O >> $ps
# measured data
imped2gmt -I$IMPED -Dxx -S | awk '{print $1, $2, $4}' | \
psxy -JX -R -Ss5p -Ey0p/0.25p/0 -G0 -K -O >> $ps

imped2gmt -I$IMPED -Dxx -S | awk '{print $1, $3, $4}' | \
psxy -JX -R -St5p -Ey0p/0.25p/100 -G100 -K -O >> $ps

# model
imped2gmt -I$IMPED -Dexx -S | awk '{print $1, $2}' | \
psxy -JX -R -W0.5p/0 -K -O >> $ps

imped2gmt -I$IMPED -Dexx -S | awk '{print $1, $3}' | \
psxy -JX -R -W0.5p/100 -K -O >> $ps

# ZXY
psbasemap -X6.6c -JX5.6cl/4.8c -R$TMIN/$TMAX/${MIN_Z[$XY]}/${MAX_Z[$XY]} -Ba1p/a${ANOTY}:"Zxy":wsnE -K -O >> $ps
# dados medidos
imped2gmt -I$IMPED -Dxy -S | awk '{print $1, $2, $4}' | \
psxy -JX -R -Ss5p -Ey0p/0.25p/0 -G0 -K -O >> $ps

imped2gmt -I$IMPED -Dxy -S | awk '{print $1, $3, $4}' | \
psxy -JX -R -St5p -Ey0p/0.25p/100 -G100 -K -O >> $ps

# dados estimados
imped2gmt -I$IMPED -Dexy -S | awk '{print $1, $2}' | \
psxy -JX -R -W0.5p/0 -K -O >> $ps

imped2gmt -I$IMPED -Dexy -S | awk '{print $1, $3}' | \
psxy -JX -R -W0.5p/100 -K -O >> $ps

# ZYY
psbasemap -Y-5.8c -JX5.6cl/4.8c -R$TMIN/$TMAX/${MIN_Z[$YY]}/${MAX_Z[$YY]} -Ba1p:"Period (s)":/a${ANOTY}:"Zyy":wSnE -K -O >> $ps
# measured data
imped2gmt -I$IMPED -Dyy -S | awk '{print $1, $2, $4}' | \
psxy -JX -R -Ss5p -Ey0p/0.25p/0 -G0 -K -O >> $ps

imped2gmt -I$IMPED -Dyy -S | awk '{print $1, $3, $4}' | \
psxy -JX -R -St5p -Ey0p/0.25p/100 -G100 -K -O >> $ps

# model
imped2gmt -I$IMPED -Deyy -S | awk '{print $1, $2}' | \
psxy -JX -R -W0.5p/0 -K -O >> $ps

imped2gmt -I$IMPED -Deyy -S | awk '{print $1, $3}' | \
psxy -JX -R -W0.5p/100 -K -O >> $ps

# ZYX
psbasemap -X-6.6c -JX5.6cl/4.8c -R$TMIN/$TMAX/${MIN_Z[$YX]}/${MAX_Z[$YX]} -Ba1p:"Period (s)":/a${ANOTY}:"Zyx":WSne -K -O >> $ps
# measured data
imped2gmt -I$IMPED -Dyx -S | awk '{print $1, $2, $4}' | \
psxy -JX -R -Ss5p -Ey0p/0.25p/0 -G0 -K -O >> $ps

imped2gmt -I$IMPED -Dyx -S | awk '{print $1, $3, $4}' | \
psxy -JX -R -St5p -Ey0p/0.25p/100 -G100 -K -O >> $ps

# model
imped2gmt -I$IMPED -Deyx -S | awk '{print $1, $2}' | \
psxy -JX -R -W0.5p/0 -K -O >> $ps

imped2gmt -I$IMPED -Deyx -S | awk '{print $1, $3}' | \
psxy -JX -R -W0.5p/100 -K -O >> $ps

# Legends

echo "0.4 0.5" | psxy -Y4.8 -R0/12.2/0/1 -Jx1 -Ss5p -G0 -K -O >> $ps
echo "0.4 0.5 8 0 0 ML Real Data" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "3.6 0.5" | psxy -R -Jx -St5p -G100 -K -O >> $ps
echo "3.6 0.5 8 0 0 ML Imaginary Data" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "6.6 0.5 0 0.6 " | psxy -R -Jx -Sv0p/0p/0p -G0 -K -O >> $ps
echo "7.0 0.5 8 0 0 ML Real Fit" | pstext -R -Jx -D0.2c/0c -K -O >> $ps

echo "9.8  0.5 0 0.6" | psxy -R -Jx -Sv0p/0p/0p -G100 -K -O >> $ps
echo "10.2 0.5 8 0 0 ML Imaginary Fit" | pstext -R -Jx -D0.2c/0c -O >> $ps

ps2raster $ps -A -P -Tg
if [[ -n $VIEWER_PNG ]] ; then
    $VIEWER_PNG ${ps/.ps/.png}&
else
    echo "figure ${ps/.ps/.png} done"
fi
rm -rf $GMT_TMPDIR
