#!/bin/csh

set FILEIN=gmt.mdl
rebocc_mdl2gmt -Iteste.out -O$FILEIN -L
set OUTFILE=gmt_mdl.ps
set HMAX=30

# configura tamanho das letras
gmtset HEADER_FONT_SIZE 16p ANOT_FONT_SIZE 12p LABEL_FONT_SIZE 14p

makecpt -I -Cgray -T1./4.0/0.25 > colors.cpt

# escala de cores
psscale -D8.75c/0.0c/15c/0.5ch -Ccolors.cpt -Ba1f0.25:"log(@~r@~)":/:"@~W@~.m":  -K -V > $OUTFILE

# grafico da parte central linear do modelo
psbasemap -Y1.5c -R0/50/0/$HMAX -Jx0.25c/-0.25c -Ba10f2:"dist\342ncia (m)":/a5f2:"profundidade (m)":nSeW -K -O -V >> $OUTFILE
# com grade
psxy $FILEIN -R0/50/0/$HMAX -Jx -M -H -L -Ccolors.cpt -W0.1p/0 -K -O -V >> $OUTFILE
awk '{if($1!=">"){print $1+10,$2}else{print $1}}'  teste.pol | psxy -R -Jx -M -L -W1p/0 -O >> $OUTFILE

# retorna aos valores defaults
gmtset HEADER_FONT_SIZE 36p ANOT_FONT_SIZE 14p LABEL_FONT_SIZE 24p

#ggv $OUTFILE&
ps2eps -f -R + $OUTFILE
awk 'BEGIN{cmd=sprintf("convert -density 150x150 %seps %spng\n",substr("'$OUTFILE'",1,index("'$OUTFILE'",".ps")),substr("'$OUTFILE'",1,index("'$OUTFILE'",".ps")));system(cmd)}'
awk 'BEGIN{cmd=sprintf("eog %spng&\n",substr("'$OUTFILE'",1,index("'$OUTFILE'",".ps")));system(cmd)}'
