      DOUBLE PRECISION FUNCTION X02AHF(X)
C     MARK 9 RELEASE. NAG COPYRIGHT 1981.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     * MAXIMUM ARGUMENT FOR SIN AND COS *
C     RETURNS THE LARGEST POSITIVE REAL NUMBER MAXSC SUCH THAT
C     SIN(MAXSC) AND COS(MAXSC) CAN BE SUCCESSFULLY COMPUTED
C     BY THE COMPILER SUPPLIED SIN AND COS ROUTINES.
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION                 X
      DOUBLE PRECISION X02CON
      DATA X02CON /1.42724769270596D+45 /
C     .. Executable Statements ..
      X02AHF = X02CON
      RETURN
      END
