      INTEGER FUNCTION X02BEF(X)
C     NAG COPYRIGHT 1975
C     MARK 4.5 RELEASE
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     * MAXDEC *
C     RETURNS THE MAXIMUM NUMBER OF DECIMAL DIGITS THAT CAN BE
C     ACCURATELY REPRESENTED IN THE COMPUTER OVER THE WHOLE RANGE
C     OF FLOATING-POINT NUMBERS.
C     THE X PARAMETER IS NOT USED.
C     .. Scalar Arguments ..
      DOUBLE PRECISION        X
C     .. Executable Statements ..
C     FOR ICL 1900
C     X02BEF = 11
      X02BEF =    15
      RETURN
      END
