      INTEGER FUNCTION X02BBF(X)
C     NAG COPYRIGHT 1975
C     MARK 4.5 RELEASE
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     * MAXINT *
C     RETURNS THE LARGEST INTEGER REPRESENTABLE ON THE COMPUTER
C     THE X PARAMETER IS NOT USED
C     .. Scalar Arguments ..
      DOUBLE PRECISION        X
C     .. Executable Statements ..
C     FOR ICL 1900
C      X02BBF = 8388607
      X02BBF =           2147483647
      RETURN
      END
