      INTEGER FUNCTION X02CAZ(X)
C     MARK 17 RELEASE. NAG COPYRIGHT 1995.
C     Originally called X02CAF
C     * ACTIVE SET SIZE *
C     IN A NON-PAGED ENVIRONMENT, RETURNS ZERO.
C     IN A PAGED ENVIRONMENT, RETURNS A SAFE UNDERESTIMATE OF THE
C     AMOUNT OF ACTUAL (AS OPPOSED TO VIRTUAL) STORAGE THAT IS
C     EXPECTED TO BE AVAILABLE TO A PROGRAM RUNNING UNDER TYPICAL
C     CONDITIONS (THE EXPECTED ACTIVE SET SIZE OR WORKING SET SIZE).
C     THE AMOUNT OF STORAGE IS GIVEN AS THE NUMBER OF REAL
C     VARIABLES THAT CAN BE STORED IN IT. IT IS IMPORTANT THAT
C     THE VALUE SHOULD BE AN UNDERESTIMATE RATHER THAN AN
C     OVERESTIMATE. THE VALUE IS USED BY LINEAR ALGEBRA ROUTINES TO
C     DETERMINE HOW MANY COLUMNS OF A MATRIX CAN BE HANDLED TOGETHER
C     AS A BLOCK IN THE EXPECTATION THAT THE WHOLE BLOCK CAN FIT
C     INTO ACTUAL STORAGE.
C     THE PRECISE VALUE IS NOT CRITICAL. IT DOES NOT AFFECT THE
C     NUMERICAL RESULTS, BUT MERELY THE AMOUNT OF PAGING PERFORMED
C     BY SOME ROUTINES WHEN SOLVING LARGE PROBLEMS IN A PAGED
C     ENVIRONMENT. IF IN DOUBT, SET THE VALUE TO ZERO.
C     ***** THE VALUE MAY VARY BETWEEN INSTALLATIONS *****
C     .. Scalar Arguments ..
      DOUBLE PRECISION        X
C     .. Executable Statements ..
      X02CAZ =      50000
      RETURN
      END
