      DOUBLE PRECISION FUNCTION S15ABF(X,IFAIL)
C     MARK 5A REVISED - NAG COPYRIGHT 1976
C     MARK 5C REVISED
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 14 REVISED. IER-753 (DEC 1989).
C     CUMULATIVE NORMAL DISTRIBUTION P(X)
C     ******************************************************************
C     TO SELECT THE CORRECT VALUE FOR A PARTICULAR MACHINE-RANGE,
C     ACTIVATE THE STATEMENT CONTAINED IN A COMMENT BEGINNING  CDD ,
C     WHERE  DD  IS THE APPROXIMATE NUMBER OF SIGNIFICANT DECIMAL
C     DIGITS REPRESENTED BY THE MACHINE.
C     DELETE THE ILLEGAL DUMMY STATEMENT OF THE FORM
C     * EXPANSION (DATA) *
C     ******************************************************************
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION                 X
      INTEGER                          IFAIL
C     .. Local Scalars ..
      DOUBLE PRECISION                 RRTWO
C     .. External Functions ..
      DOUBLE PRECISION                 S15ADF
      EXTERNAL                         S15ADF
C     .. Data statements ..
C     PRECISION DEPENDENT CONSTANTS
C      * EXPANSION (DATA) *
C08   DATA RRTWO/7.0710678D-1/
C12   DATA RRTWO/7.07106781187D-1/
C14   DATA RRTWO/7.0710678118655D-1/
      DATA RRTWO/7.071067811865475D-1/
C18   DATA RRTWO/7.07106781186547524D-1/
C     .. Executable Statements ..
C
C     NO FAILURE EXITS - IFAIL SET TO ZERO IN S15ADF
      S15ABF = 0.5D0*S15ADF(-X*RRTWO,IFAIL)
      RETURN
C
      END
