% popup menu for eigenvector plotting
hfig_evec_menu = figure('Position',[300,300,250,205],...
    'Name','Eigenvector Plot Options','NumberTitle','off');
pos0=[5 50 240 125];
pos1=[20 100 140 20];
pos2=[170 100 70 20];
pos3=[20 75 140 20];
pos4=[170 75 70 20];
pos6=[50 125 150 20];
pos7=[50 150 150 20];
pos8=[20 20 50 20];
pos9=[180 20 50 20];
%
rho_ref_old = rho_ref;
n_evec = length(ivec);
n_evec_old = n_evec;
l_ellipse_old = l_ellipse;
snr_units_old = snr_units;
str = 'String';

fr=uicontrol(gcf,'Style','frame','Position',pos0,...
'BackgroundColor',[0.5 0.5 0.5]);
%
tx1=uicontrol(gcf,'Style','text','String',...
'# of evecs :       ','Position',pos1,'BackgroundColor',[0.5 0.5 0.5]);
ed1=uicontrol(gcf,'Style','edit','String',n_evec,'Position',pos2,...
'CallBack','n_evec=str2num(get(ed1,str));');
%
tx2=uicontrol(gcf,'Style','text','String',...
'reference rho:      ','Position',pos3,'BackgroundColor',[0.5 0.5 0.5]);
ed2=uicontrol(gcf,'Style','edit','String',rho_ref,'Position',pos4,...
'CallBack','rho_ref=str2num(get(ed2,str));');
%
sc=uicontrol(gcf,'Style','radio','String','SNR Units','Value',snr_units,...
'Position',pos6,...
'CallBack','snr_units=1-snr_units; set(sc,''Value'',snr_units);');
%
pe=uicontrol(gcf,'Style','radio',...
	'String','Polarization Ellipse',...
	'Value',l_ellipse,...
	'Position',pos7,...
	'CallBack','l_ellipse=1-l_ellipse; set(pe,''Value'',l_ellipse);');
%
pb_apply=uicontrol(gcf,'Style','push','String','Apply',...
 'Position',pos8,...
'CallBack','close(gcf); ivec = [1:n_evec];');
pb_cancel=uicontrol(gcf,'Style','push',...
	'String','Cancel',...
	'Position',pos9,...
	'CallBack',['close(gcf);rho_ref=rho_ref_old;'...
	   'snr_units=snr_units_old;n_evec=n_evec_old;'...
	   'l_ellipse=l_ellipse_old;']);
