slide_min = log10(periods(1)); 
slide_max = log10(periods(nbt));
h_slider = uicontrol('Parent',hfig,'Style','slider',...
          'Units','normalized','Position',[.05,.30,.9,.02], ...   
          'Max',slide_max,'Min',slide_min,'CallBack','evec');
