      SUBROUTINE D01BBF(WTFUN,A,B,ITYPE,NPTS,WEIGHT,ABSCIS,IFAIL)
C     MARK 7 RELEASE. NAG COPYRIGHT 1978.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     RETURNS WEIGHTS AND PIVOTS FOR ONE GAUSS-WTFUN FORMULA IF
C     STORED
C     IFAIL = 1 - THE NPTS RULE IS NOT AMONG THOSE STORED
C     ( WEIGHT,ABSCIS EVALUATED FOR LARGEST VALID NPTS LESS THAN
C     REQUESTED VALUE)
C     IFAIL = 2 - VALUES OF A OR B INVALID
C     ( ALL WEIGHTS AND ABSCISSAE RETURNED AS ZERO)
C     IFAIL = 3 - UNDERFLOW IN EVALUATING LAGUERRE OR HERMITE
C     NORMAL WEIGHTS
C     ( THE UNDERFLOWING WEIGHTS ARE RETURNED AS ZERO)
C
C     THE WEIGHTS AND ABSCISSAE RETURNED DEPEND ON A AND B.
C
C     WTFUN
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='D01BBF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  A, B
      INTEGER           IFAIL, ITYPE, NPTS
C     .. Array Arguments ..
      DOUBLE PRECISION  ABSCIS(NPTS), WEIGHT(NPTS)
C     .. Subroutine Arguments ..
      EXTERNAL          WTFUN
C     .. Local Scalars ..
      INTEGER           IERR
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. Executable Statements ..
      CALL WTFUN(A,B,ITYPE,NPTS,WEIGHT,ABSCIS,IERR)
      IF (IERR.EQ.0) GO TO 20
      IFAIL = P01ABF(IFAIL,IERR,SRNAME,0,P01REC)
      RETURN
   20 IFAIL = 0
      RETURN
      END
