      SUBROUTINE D01GBF(NUMVAR,A,B,MINPTS,MAXPTS,FUNCTN,RELEPS,RELERR,
     *                  LENWRK,WRKSTR,FINVAL,IFAIL)
C     MARK 10 RELEASE. NAG COPYRIGHT 1982.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     ADAPTIVE MONTE-CARLO MULTIDIMENSIONAL INTEGRATION SUBROUTINE
C     THIS SUBROUTINE COMPUTES AN APPROXIMATION TO THE INTEGRAL
C
C      B(1) B(2)     B(NUMVAR)
C     I    I    ... I   FUNCTN(NUMVAR,X) DX(NUMVAR)...DX(2)DX(1)
C      A(1) A(2)     A(NUMVAR)
C
C     ***** INPUT PARAMETERS
C
C     NUMVAR  INTEGER NUMBER OF VARIABLES, MUST EXCEED 0
C     A       REAL ARRAY OF LOWER LIMITS, WITH DIMENSION NUMVAR
C     B       REAL ARRAY OF UPPER LIMITS, WITH DIMENSION NUMVAR
C     MINPTS  INTEGER MINIMUM NUMBER OF FUNCTION EVALUATIONS TO BE
C             ALLOWED. MINPTS MUST BE LESS THAN MAXPTS.
C             IF MINPTS IS NEGATIVE, THIS SPECIFIES
C              A)A CONTINUATION OF THE PREVIOUS CALCULATION USING
C                THE SAME INTEGRAND, OR
C              B)THE BEGINNING OF A NEW CALCULATION WITH A SIMILAR
C                INTEGRAND BUT USING THE SUBDIVISION THAT WAS USED
C                AT THE END OF THE PREVIOUS CALL OF D01GBF
C     MAXPTS  INTEGER MAXIMUM NUMBER OF FUNCTION EVALUATIONS TO BE
C             ALLOWED, WHICH MUST EXCEED MINPTS AND MUST BE AT LEAST
C             4*NUMVAR+4. IN THE CONTINUATION CASE THIS IS THE
C             NUMBER OF NEW FUNCTION EVALUATIONS TO BE ALLOWED.
C     FUNCTN  REAL EXTERNALLY DECLARED USER DEFINED FUNCTION
C             INTEGRAND. IT MUST HAVE PARAMETERS (NUMVAR,X), WHERE X
C             IS A REAL ARRAY OF DIMENSION NUMVAR.
C     RELEPS  REAL REQUIRED RELATIVE ACCURACY
C     LENWRK  INTEGER LENGTH OF ARRAY WRKSTR OF WORKING STORAGE,
C             WHICH MUST BE AT LEAST 10*NUMVAR WITH RECOMMENDED
C             VALUE 3*NUMVAR*((MAXPTS/4)**(1/NUMVAR))+7*NUMVAR
C     WRKSTR  REAL ARRAY OF WORKING STORAGE OF DIMENSION(LENWRK).
C             WHEN MINPTS IS SET NEGATIVE FOR CASE B), THEN
C             WRKSTR(LENWRK) MUST BE SET TO ZERO.  IN CASES A) AND
C             B) OTHER VALUES OF WRKSTR MUST NOT BE CHANGED BETWEEN
C             SUCCESSIVE CALLS.
C     IFAIL   INTEGER NAG FAILURE PARAMETER
C
C     ***** OUTPUT PARAMETERS
C
C     WRKSTR  REAL ARRAY OF WORKING STORAGE OF DIMENSION (LENWRK),
C             ON EXIT THIS CONTAINS INFORMATION WHICH COULD BE USED
C             IN LATER CALLS OF D01GBF WITH THE SAME OR A SIMILAR
C             INTEGRAND.
C     RELERR  REAL ESTIMATED RELATIVE ACCURACY OF FINVAL
C     FINVAL  REAL ESTIMATED VALUE OF INTEGRAL.  IN THE CONTINUATION
C             CASE A FINVAL MUST NOT BE CHANGED BETWEEN SUCCESSIVE
C             CALLS.
C     IFAIL   IFAIL=0 FOR NORMAL EXIT, WHEN ESTIMATED RELATIVE
C                     ACCURACY IS LESS THAN RELEPS WITH FEWER THAN
C                     MAXPTS FUNCTION CALLS MADE.
C             IFAIL=1 IF NUMVAR.LT.1, MINPTS.GE.MAXPTS,
C                     LENWRK.LT.10*NUMVAR OR MAXPTS.LT.4*(NUMVAR+1)
C                     OR RELEPS.LT.0.0.
C             IFAIL=2 IF MAXPTS WAS TOO SMALL FOR D01GBF TO OBTAIN
C                     THE REQUIRED ACCURACY.  IN THIS CASE D01GBF
C                     RETURNS A VALUE OF FINVAL WITH ESTIMATED
C                     RELATIVE ACCURACY RELERR.
C
C     FAIL FOR TOO MANY OR TOO FEW VARIABLES OR LENWRK TOO SMALL OR
C     MINPTS.GE.MAXPTS OR MAXPTS.LT.4*NUMVAR+4
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='D01GBF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  FINVAL, RELEPS, RELERR
      INTEGER           IFAIL, LENWRK, MAXPTS, MINPTS, NUMVAR
C     .. Array Arguments ..
      DOUBLE PRECISION  A(NUMVAR), B(NUMVAR), WRKSTR(LENWRK)
C     .. Function Arguments ..
      DOUBLE PRECISION  FUNCTN
      EXTERNAL          FUNCTN
C     .. Local Scalars ..
      INTEGER           IERROR
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          D01GBZ
C     .. Executable Statements ..
      IERROR = 1
      RELERR = 1.0D0
      IF (NUMVAR.LT.1) GO TO 20
      IF (LENWRK.LT.10*NUMVAR) GO TO 20
      IF (MINPTS.GE.MAXPTS) GO TO 20
      IF (MAXPTS.LT.4*NUMVAR+4) GO TO 20
      IF (RELEPS.LT.0.0D0) GO TO 20
      CALL D01GBZ(NUMVAR,A,B,MINPTS,MAXPTS,FUNCTN,RELEPS,RELERR,
     *            WRKSTR(1),WRKSTR(NUMVAR+1),WRKSTR(2*NUMVAR+1)
     *            ,WRKSTR(3*NUMVAR+1),WRKSTR(4*NUMVAR+1)
     *            ,WRKSTR(5*NUMVAR+1),WRKSTR(6*NUMVAR+1)
     *            ,LENWRK-7*NUMVAR,WRKSTR(7*NUMVAR+1),FINVAL,IERROR)
   20 IFAIL = P01ABF(IFAIL,IERROR,SRNAME,0,P01REC)
      RETURN
      END
