      SUBROUTINE D01PAF(NUMVAR,VERTEX,IV1,IV2,INTGND,MINORD,MAXORD,
     *                  INTVLS,ESTERR,IFAIL)
C     MARK 10 RELEASE. NAG COPYRIGHT 1982.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MULTIDIMENSIONAL SIMPLEX ROMBERG INTEGRATION SUBROUTINE
C       SUBROUTINE FOR COMPUTING INTEGRALS OF THE TYPE
C
C            I F(X) DX(1)DX(2)...DX(NUMVAR)
C             S
C
C       WHERE S IS A NUMVAR DIMENSIONAL SIMPLEX
C
C     **************  PARAMETERS FOR D01PAF  ***********************
C     NUMVAR  INTEGER NUMBER OF VARIABLES, MUST EXCEED 1.
C     VERTEX  REAL ARRAY OF SIMPLEX VERTICES WITH DIMENSION
C             (IV1,IV2). VERTEX(I,J) IS THE JTH COORDINATE OF THE
C             ITH VERTEX
C     IV1     INTEGER FIRST DIMENSION OF VERTEX, MUST BE
C             .GE. NUMVAR+1.
C     IV2     INTEGER SECOND DIMENSION OF VERTEX, MUST BE
C             .GE. 2*NUMVAR+2.
C     INTGND  EXTERNALLY DECLARED USER DEFINED REAL FUNCTION
C             INTEGRAND.
C             IT MUST HAVE PARAMETERS (NUMVAR,X), WHERE X IS A REAL
C             ARRAY WITH DIMENSION NUMVAR.
C     MINORD  INTEGER MINIMUM ORDER PARAMETER, MUST BE AT LEAST 0
C             AND LESS THAN MAXORD.  WHEN MINORD IS NOT 0 THE
C             SUBROUTINE ASSUMES A PREVIOUS CALL OR CALLS OF THE
C             SUBROUTINE HAVE BEEN USED TO COMPUTE
C             INTVLS(1), INTVLS(2),..., INTVLS(MINORD).
C             ON EXIT, MINORD IS SET EQUAL TO MAXORD.
C     MAXORD  INTEGER MAXIMUM ORDER PARAMETER, MUST BE GREATER THAN
C             MINORD THE SUBROUTINE COMPUTES INTVLS(MINORD+1),
C             INTVLS(MINORD+2), ..., INTVLS(MAXORD).
C     INTVLS  REAL ARRAY OF DIMENSION(MAXORD).  UPON SUCCESSFUL EXIT
C             INTVLS(1), INTVLS(2),..., INTVLS(MAXORD) ARE
C             APPROXIMATIONS TO THE INTEGRAL.  INTVLS(J) WILL BE AN
C             APPROXIMATION OF POLYNOMIAL DEGREE 2*J-1.
C     ESTERR  REAL ABSOLUTE ERROR ESTIMATE
C     IFAIL   INTEGER FAILURE OUTPUT PARAMETER
C             IFAIL=0 FOR SUCCESSFUL TERMINATION OF THE SUBROUTINE
C             IFAIL=1 WHEN PARAMETERS NUMVAR,MINORD,MAXORD,
C                     IV1 OR IV2 ARE OUT OF RANGE
C             IFAIL=2 WHEN F03AAF FAILS FROM UNDERFLOW OR OVERFLOW
C                     IN THE COMPUTATION OF THE SIMPLEX VOLUME
C     **************************************************************
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='D01PAF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  ESTERR
      INTEGER           IFAIL, IV1, IV2, MAXORD, MINORD, NUMVAR
C     .. Array Arguments ..
      DOUBLE PRECISION  INTVLS(MAXORD), VERTEX(IV1,IV2)
C     .. Function Arguments ..
      DOUBLE PRECISION  INTGND
      EXTERNAL          INTGND
C     .. Local Scalars ..
      INTEGER           IERROR
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          D01PAZ
C     .. Executable Statements ..
      IERROR = 1
      IF (NUMVAR.GE.IV1) GO TO 20
      IF (NUMVAR.LT.2) GO TO 20
      IF (MINORD.LT.0 .OR. MINORD.GE.MAXORD) GO TO 20
      IF (IV2.LT.2*NUMVAR+2) GO TO 20
      CALL D01PAZ(NUMVAR,IV1,VERTEX(1,1)
     *            ,INTGND,MINORD,MAXORD,INTVLS,ESTERR,VERTEX(1,NUMVAR+1)
     *            ,VERTEX(1,2*NUMVAR+1),VERTEX(1,2*NUMVAR+2),IERROR)
   20 IFAIL = P01ABF(IFAIL,IERROR,SRNAME,0,P01REC)
      RETURN
      END
