      SUBROUTINE D02QFS(T,YINT,YPINT,NEQ,X,YY,P,PHI)
C     MARK 13 RELEASE. NAG COPYRIGHT 1988.
C
C
C     D02QFS DOES THE INTERPOLATION FOR THE ROOT FINDING TASK IN
C     D02QFF/D02QGF.
C     IT DEFINES THE GENERIC ROUTINE RINTRP CALLED BY SUBROUTINE D02QFV.
C     BECAUSE OF DIFFERENT INTERPOLATION SCHEMES WITH EACH OF THE
C     INTEGRATION METHODS, THE VARIOUS REPRESENTATIVES FOR RINTRP MUST
C     NECESSARILY BE DIFFERENT.
C
C
C     DATE WRITTEN   840908   (YYMMDD)
C     REVSION DATE   850101   (YYMMDD)
C     AUTHOR WATTS, H. A., (SNLA)
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION  T, X
      INTEGER           NEQ
C     .. Array Arguments ..
      DOUBLE PRECISION  P(NEQ), PHI(NEQ,*), YINT(NEQ), YPINT(NEQ),
     *                  YY(NEQ)
C     .. Scalars in Common ..
      DOUBLE PRECISION  HOLD, TOLD, TSTAR, TWOU, XOLD, XSAVE
      INTEGER           IBEGIN, IINTEG, INFLOP, INIT, IQUIT, ITOL,
     *                  ITSTOP, IVC, KGI, KLE4, KOLD, KORD, KPREV,
     *                  KSTEPS, NS
      LOGICAL           INTOUT, NORND, PHASE1, START, STIFF
C     .. Arrays in Common ..
      DOUBLE PRECISION  ALPHA(12), BETA(12), G(13), GI(11), PSI(12),
     *                  SIG(13), V(12), W(12)
      INTEGER           IV(10)
C     .. External Subroutines ..
      EXTERNAL          D02QFR
C     .. Common blocks ..
      COMMON            /AD02QF/ALPHA, BETA, PSI, V, W, SIG, G, GI,
     *                  XOLD, HOLD, TOLD, XSAVE, TSTAR, TWOU, INIT,
     *                  IBEGIN, ITOL, IINTEG, ITSTOP, INFLOP, IQUIT, IV,
     *                  NS, KORD, KOLD, KSTEPS, KLE4, KPREV, IVC, KGI,
     *                  START, PHASE1, NORND, STIFF, INTOUT
C     .. Save statement ..
      SAVE              /AD02QF/
C     .. Executable Statements ..
C
C     CALL SINTRP(X,YY,T,YINT,YPINT,NEQ,NEQ,KOLD,PHI,IVC,IV,KGI,GI,
C                 ALPHA,G,W,XOLD,P)
      CALL D02QFR(X,YY,T,YINT,YPINT,NEQ,NEQ,KOLD,PHI,IVC,IV,KGI,GI,
     *            ALPHA,G,W,XOLD,P)
C     CALL SINTRP(X,YY,T,YINT,YPINT,NEQ,KOLD,PHI,IVC,IV,KGI,GI,ALPHA,G,
C                 W,XOLD,P)
C
      RETURN
C
C
C     END OF D02QFS (RINTAM)
C
C
      END
