import Namespace Reference
funções para importar os valores de impedâncias de arquivos
Functions
transfer_function::impedance_collection_type::size_type number_of_transfer_functions (std::ifstream &file)
Retorna o número de funções de transferência em file.
void import_impedances (transfer_function::impedance_collection_type &tf, std::ifstream &file)
função para adquirir as funções de transferência de um arquivo
bool is_egbert (std::ifstream &file)
verifica se file é do tipo egbert
bool is_jones (std::ifstream &file)
verifica se file é do tipo jones
Detailed Description
funções para importar os valores de impedâncias de arquivos
Function Documentation
void import::import_impedances (transfer_function::impedance_collection_type & tf, std::ifstream & file)
função para adquirir as funções de transferência de um arquivo
Parameters:
$\rightarrow$ tf container com as funções de transferência
$\leftarrow$ file arquivo em um formato conhecido
References import_jones::import_impedances(), import_egbert::import_impedances(), is_egbert(), and is_jones().
bool import::is_egbert (std::ifstream & file)
verifica se file é do tipo egbert
Um arquivo é identificado como do tipo egbert se conter uma linha que inicie com o texto ` Transfer Functions` (o espaço no início é importante
Parameters:
$\leftarrow$ file arquivo
Returns: true se file for do tipo egbert
Referenced by import_impedances(), and number_of_transfer_functions().
bool import::is_jones (std::ifstream & file)
verifica se file é do tipo jones
Um arquivo é identificado como do tipo jones se conter uma linha que inicie com o texto `>AZIMUTH =`
Parameters:
$\leftarrow$ file arquivo
Returns: true se file for do tipo jones
Referenced by import_impedances(), and number_of_transfer_functions().
transfer_function::impedance_collection_type::size_type import::number_of_transfer_functions (std::ifstream & file)
Retorna o número de funções de transferência em file.
Precondition: file deve ser um arquivo válido
Invariant: a posição de leitura de file
Parameters:
$\leftarrow$ file stream de um arquivo válido no formato jones
Returns: o número de funções de transferência em file
Todo implementar exception
References is_egbert(), is_jones(), import_jones::number_of_transfer_functions(), and import_egbert::number_of_transfer_functions().