import_egbert Namespace Reference
funções para ler um arquivo do tipo egbert
Functions
int number_of_transfer_functions (std::ifstream &egbert_file)
Retorna o número de funções de transferência em egbert_file.
void import_impedances (transfer_function::impedance_collection_type &tf, std::ifstream &egbert_file)
função para adquirir as funções de transferência de um arquivo
void import_tipper_vector_value (std::vector< transfer_function::complex_type > &tv, std::ifstream &egbert_file)
Le o valor do próximo tipper a partir da posição atual de egbert_file.
void import_impedance_tensor_value (gmm::dense_matrix< transfer_function::complex_type > &imp_tensor, std::ifstream &egbert_file)
Le o valor do próximo tensor de impedância a partir da posição atual de egbert_file.
void import_inverse_coherent_signal_power_matrix (transfer_function::complex_matrix_type &matrix, std::ifstream &egbert_file)
Le o valor da próxima `inverse coherent signal power matrix` a partir da posição de egbert_file.
void import_residual_covariance_matrix (transfer_function::complex_matrix_type &matrix, std::ifstream &egbert_file)
Le o valor da próxima matriz de covariância residual a partir da posição de egbert_file.
void build_tipper (transfer_function::tipper_vector_type &tipper, std::vector< transfer_function::complex_type > const &tipper_value, gmm::dense_matrix< transfer_function::complex_type > const &s_matrix, gmm::dense_matrix< transfer_function::complex_type > const &n_matrix)
Constrói o tipper (valor e incerteza) através do seu valor e das matrizes de.
void build_impedance (transfer_function::impedance_tensor_type &imp, gmm::dense_matrix< transfer_function::complex_type > const &impedance_value, gmm::dense_matrix< transfer_function::complex_type > const &s_matrix, gmm::dense_matrix< transfer_function::complex_type > const &n_matrix)
Constrói o tensor de impedância (valor e incerteza).
void import_transfer_function (transfer_function::real_type &period, transfer_function::tipper_vector_type &tipper, transfer_function::impedance_tensor_type &impedance, std::ifstream &egbert_file)
Le, a partir da posição de egbert_file o valor do período tipper e da impedância.
Detailed Description
funções para ler um arquivo do tipo egbert
Function Documentation
void import_egbert::build_impedance (transfer_function::impedance_tensor_type & imp, gmm::dense_matrix< transfer_function::complex_type > const & impedance_value, gmm::dense_matrix< transfer_function::complex_type > const & s_matrix, gmm::dense_matrix< transfer_function::complex_type > const & n_matrix)
Constrói o tensor de impedância (valor e incerteza).
Parameters:
$\rightarrow$ imp
$\leftarrow$ impedance_value
$\leftarrow$ s_matrix
$\leftarrow$ n_matrix
Referenced by import_transfer_function().
void import_egbert::build_tipper (transfer_function::tipper_vector_type & tipper, std::vector< transfer_function::complex_type > const & tipper_value, gmm::dense_matrix< transfer_function::complex_type > const & s_matrix, gmm::dense_matrix< transfer_function::complex_type > const & n_matrix)
Constrói o tipper (valor e incerteza) através do seu valor e das matrizes de.
covariância
Parameters:
$\rightarrow$ tipper
$\leftarrow$ tipper_value
$\leftarrow$ s_matrix
$\leftarrow$ n_matrix
Referenced by import_transfer_function().
void import_egbert::import_impedance_tensor_value (gmm::dense_matrix< transfer_function::complex_type > & imp_tensor, std::ifstream & egbert_file)
Le o valor do próximo tensor de impedância a partir da posição atual de egbert_file.
Parameters:
imp_tensor tensor de impedância
egbert_file arquivo do tipo egbert
Referenced by import_transfer_function().
void import_egbert::import_impedances (transfer_function::impedance_collection_type & tf, std::ifstream & egbert_file)
função para adquirir as funções de transferência de um arquivo
Parameters:
$\rightarrow$ tf container com as funções de transferência
$\leftarrow$ egbert_file arquivo egbert
References import_transfer_function(), and number_of_transfer_functions().
Referenced by import::import_impedances().
void import_egbert::import_inverse_coherent_signal_power_matrix (transfer_function::complex_matrix_type & matrix, std::ifstream & egbert_file)
Le o valor da próxima `inverse coherent signal power matrix` a partir da posição de egbert_file.
Parameters:
matrix inverse coherent signal power matrix
egbert_file arquivo do tipo egbert
Referenced by import_transfer_function().
void import_egbert::import_residual_covariance_matrix (transfer_function::complex_matrix_type & matrix, std::ifstream & egbert_file)
Le o valor da próxima matriz de covariância residual a partir da posição de egbert_file.
Parameters:
$\rightarrow$ matrix a matriz de covariância residual
egbert_file arquivo do tipo egbert
Referenced by import_transfer_function().
void import_egbert::import_tipper_vector_value (std::vector< transfer_function::complex_type > & tv, std::ifstream & egbert_file)
Le o valor do próximo tipper a partir da posição atual de egbert_file.
Parameters:
tv
egbert_file
Referenced by import_transfer_function().
void import_egbert::import_transfer_function (transfer_function::real_type & period, transfer_function::tipper_vector_type & tipper, transfer_function::impedance_tensor_type & impedance, std::ifstream & egbert_file)
Le, a partir da posição de egbert_file o valor do período tipper e da impedância.
Parameters:
period
tipper
impedance
egbert_file
References build_impedance(), build_tipper(), import_impedance_tensor_value(), import_inverse_coherent_signal_power_matrix(), import_residual_covariance_matrix(), and import_tipper_vector_value().
Referenced by import_impedances().
int import_egbert::number_of_transfer_functions (std::ifstream & egbert_file)
Retorna o número de funções de transferência em egbert_file.
Precondition: egbert_file deve ser um arquivo válido no formato egbert
Invariant: a posição de leitura de egbert_file
Parameters:
egbert_file stream de um arquivo válido no formato egbert
Returns: o número de funções de transferência em egbert_file
Referenced by import_impedances(), and import::number_of_transfer_functions().