import_jones Namespace Reference
funções para ler um arquivo do tipo jones
Typedefs
typedef std::map< transfer_function::real_type, transfer_function::complex_measurement_type > component_map
Conjunto de todos os valores de uma determinada componente.
typedef std::map< std::string, component_map > components_collection
Coleção de todas as componentes de um arquivo Jones.
Functions
void import_component (component_map &component, const std::string comp_string, std::ifstream &file)
importa a componente component identificada por comp_string do arquivo file
void read_components (components_collection &collection, std::ifstream &file)
transfere todos os componentes de file em collection
bool periods_are_valid (components_collection const &collection)
confirma se os periodos do arquivo estão validos
bool periods_are_equal (components_collection::const_iterator const first_it, components_collection::const_iterator const second_it)
Verifica se todos os periodos de first_it estão em second_it.
void skip_comment_block (std::ifstream &file)
salta o bloco de comentário de file
void skip_information_block (std::ifstream &file)
salta o bloco de informação de file
transfer_function::impedance_collection_type::size_type number_of_transfer_functions (std::ifstream &file)
Retorna o número de funções de transferência em file.
void import_impedances (transfer_function::impedance_collection_type &tf, std::ifstream &file)
função para adquirir as funções de transferência de um arquivo
Detailed Description
funções para ler um arquivo do tipo jones
Typedef Documentation
typedef std::map< transfer_function::real_type, transfer_function::complex_measurement_type > import_jones::component_map
Conjunto de todos os valores de uma determinada componente.
A chave do mapa é período é o valor mapeado é o valor da componente daquele período
typedef std::map< std::string, component_map > import_jones::components_collection
Coleção de todas as componentes de um arquivo Jones.
A chave do mapa é um std::string que identifica a componente e o valor mapeado é um std::map com os todos os valores da componente identificada pela string
Function Documentation
void import_jones::import_component (component_map & component, const std::string comp_string, std::ifstream & file)
importa a componente component identificada por comp_string do arquivo file
Os arquivos do tipo jones identificam cada componente por um string. Quando essa string é encontrada os valores são inseridos na componente fornecida
Parameters:
$\rightarrow$ component mapa com os valores do componente
$\leftarrow$ comp_string identificação do componente (case sensitive)
$\leftarrow$ file arquivo tipo jones
Referenced by read_components().
void import_jones::import_impedances (transfer_function::impedance_collection_type & tf, std::ifstream & file)
função para adquirir as funções de transferência de um arquivo
Parameters:
$\rightarrow$ tf container com as funções de transferência
$\leftarrow$ file arquivo no formato jones
References read_components().
Referenced by import::import_impedances().
transfer_function::impedance_collection_type::size_type import_jones::number_of_transfer_functions (std::ifstream & file)
Retorna o número de funções de transferência em file.
Precondition: file deve ser um arquivo válido no formato jones
Invariant: a posição de leitura de file
Parameters:
$\leftarrow$ file stream de um arquivo válido no formato jones
Returns: o número de funções de transferência em file
References skip_comment_block(), and skip_information_block().
Referenced by import::number_of_transfer_functions().
bool import_jones::periods_are_equal (components_collection::const_iterator const first_it, components_collection::const_iterator const second_it)
Verifica se todos os periodos de first_it estão em second_it.
Note: Não verifica se os containers de first_it e second_it tem o mesmo tamanho
Parameters:
first_it
second_it
Returns:
Referenced by periods_are_valid().
bool import_jones::periods_are_valid (components_collection const & collection)
confirma se os periodos do arquivo estão validos
Se uma componente (Tzx, Tzy, Zxx, Zxy, etc.) tiver um certo período todas as demais componentes devem ter o mesmo período
Todo não é claro o que o jones calcula os erros
Parameters:
$\leftarrow$ collection vetor com as componentes a serem verificadas
Returns: true se todas as componentes de collection tiverem os mesmos períodos
References periods_are_equal().
void import_jones::read_components (components_collection & collection, std::ifstream & file)
transfere todos os componentes de file em collection
!
collection contém todas as 42 componentes possíveis, as que não estão em file tem tamanho igual a zero.
Parameters:
$\rightarrow$ collection
$\leftarrow$ file
References import_component().
Referenced by import_impedances().
void import_jones::skip_comment_block (std::ifstream & file)
salta o bloco de comentário de file
Precondition: file deve ser um arquivo válido no jones (file == true)
Postcondition: file fica posicionado após o bloco de comentário
Parameters:
file arquivo no formato jones
Referenced by number_of_transfer_functions().
void import_jones::skip_information_block (std::ifstream & file)
salta o bloco de informação de file
Precondition: file deve estar posicionado no início do bloco de informação. Essa condição pode ser consiguida com uma chamada a skip_comment_block
Postcondition: file fica posicionado após o bloco de informação
Parameters:
file arquivo no formato jones
Referenced by number_of_transfer_functions().