      SUBROUTINE F02BJF(N,A,IA,B,IB,EPS1,ALFR,ALFI,BETA,MATZ,Z,IZ,ITER,
     *                  IFAIL)
C     MARK 6 RELEASE. NAG COPYRIGHT 1977
C     MARK 6A REVISED  IER-99
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     THIS SUBROUTINE PERFORMS THE QZ ALGORITHM FOR SOLVING THE
C     GENERALIZED MATRIX EIGENVALUE PROBLEM, A*Z = LAMBDA*B*Z
C     WHERE A AND B ARE REAL SQUARE MATRICES.
C     REFERENCE
C     SIAM J.NUMER.ANAL., 10, PP241-256, 1973.
C     C. B. MOLER AND G. W. STEWART.
C
C     THIS SUBROUTINE WAS WRITTEN BY
C     W. PHILLIPS OXFORD UNIVERSITY COMPUTING SERVICE.
C     IT CALLS F02BJW, F02BJX, F02BJY AND F02BJZ WHICH
C     WERE OBTAINED FROM EISPACK.
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='F02BJF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  EPS1
      INTEGER           IA, IB, IFAIL, IZ, N
      LOGICAL           MATZ
C     .. Array Arguments ..
      DOUBLE PRECISION  A(IA,N), ALFI(N), ALFR(N), B(IB,N), BETA(N),
     *                  Z(IZ,N)
      INTEGER           ITER(N)
C     .. Local Scalars ..
      INTEGER           ISAVE
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          F02BJW, F02BJX, F02BJY, F02BJZ
C     .. Executable Statements ..
      ISAVE = IFAIL
      IFAIL = 1
      CALL F02BJW(N,A,IA,B,IB,MATZ,Z,IZ)
      CALL F02BJX(N,A,IA,B,IB,EPS1,MATZ,Z,IZ,ITER,IFAIL)
      IF (IFAIL.EQ.0) GO TO 20
      IFAIL = P01ABF(ISAVE,IFAIL,SRNAME,0,P01REC)
   20 CALL F02BJY(N,A,IA,B,IB,ALFR,ALFI,BETA,MATZ,Z,IZ)
      IF (IFAIL.NE.0) RETURN
      IF (MATZ) CALL F02BJZ(N,A,IA,B,IB,ALFR,ALFI,BETA,Z,IZ)
      RETURN
      END
