      INTEGER FUNCTION F02WDY(N,SV,TOL)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (IRKSVD)
C
C     F02WDY RETURNS THE RANK OF AN M*K MATRIX A FOLLOWING A
C     SINGULAR VALUE DECOMPOSITION OF A.
C
C     THE N=MIN(M,K) SINGULAR VALUES OF A MUST BE IN
C     DESCENDING ORDER IN THE N ELEMENT VECTOR SV. THEN F02WDY
C     RETURNS THE LARGEST INTEGER SUCH THAT
C
C     SV(F02WDY) .GT. TOL*SV(1) .
C
C     IF SV(1)=0 THEN F02WDY IS RETURNED AS ZERO.
C
C     IF TOL.LT.EPS OR TOL.GE.1 THEN THE VALUE EPS IS USED IN
C     PLACE OF TOL, WHERE EPS IS THE SMALLEST REAL FOR WHICH
C     1.0+EPS.GT.1.0 ON THE MACHINE. FOR MOST PROBLEMS THIS IS
C     UNREASONABLY SMALL AND TOL SHOULD BE CHOSEN TO
C     APPROXIMATE THE RELATIVE ERRORS IN THE ELEMENTS OF A.
C
C     IF INSTEAD SINGULAR VALUES BELOW SOME VALUE DELTA ARE TO
C     BE REGARDED AS ZERO THEN SUPPLY TOL AS DELTA/SV(1).
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION        TOL
      INTEGER                 N
C     .. Array Arguments ..
      DOUBLE PRECISION        SV(N)
C     .. Local Scalars ..
      DOUBLE PRECISION        DELTA, TL
      INTEGER                 I, IR
C     .. External Functions ..
      DOUBLE PRECISION        X02AJF
      EXTERNAL                X02AJF
C     .. Executable Statements ..
      TL = TOL
      DELTA = X02AJF()
      IF (TL.LT.DELTA .OR. TL.GE.1.0D0) TL = DELTA
C
      IR = 0
      DELTA = TL*SV(1)
C
      DO 20 I = 1, N
         IF (SV(I).LE.DELTA) GO TO 40
         IR = I
   20 CONTINUE
C
   40 F02WDY = IR
      RETURN
      END
