      SUBROUTINE F02WAX(M,N,A,NRA,WANTB,B,SV,WORK,LWORK,IFAIL)
C     MARK 16 RELEASE. NAG COPYRIGHT 1993.
C
C     This routine originally called F02WAF.
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (SVDGN1)
C     Modified by Sven to replace calls to F01QAF and F02WAZ.
C     7-Feb-1991.
C
C     F02WAX RETURNS PART OF THE SINGULAR VALUE DECOMPOSITION
C     OF THE M*N (M.GE.N) MATRIX A GIVEN BY
C
C     A = Q*(D)*(P**T) ,
C           (0)
C
C     WHERE Q AND P ARE ORTHOGONAL MATRICES AND D IS AN N*N
C     DIAGONAL MATRIX WITH NON-NEGATIVE DIAGONAL ELEMENTS,
C     THESE BEING THE SINGULAR VALUES OF A.
C
C     P**T AND THE DIAGONAL ELEMENTS OF D ARE RETURNED.
C     IF WANTB IS .TRUE. THEN (Q**T)*B IS ALSO RETURNED.
C
C     INPUT PARAMETERS.
C
C     M     - NUMBER OF ROWS OF A. M MUST BE AT LEAST N.
C
C     N     - NUMBER OF COLUMNS OF A. N MUST BE AT LEAST
C             UNITY AND MUST NOT BE LARGER THAN THAN M.
C
C     A     - THE M*N MATRIX TO BE FACTORIZED.
C
C     NRA   - ROW DIMENSION OF A AS DECLARED IN THE CALLING PROGRAM.
C             NRA MUST BE AT LEAST M.
C
C     WANTB - MUST BE .TRUE. IF (Q**T)*B IS REQUIRED.
C             IF WANTB IS .FALSE. THEN B IS NOT REFERENCED.
C
C     B     - AN M ELEMENT VECTOR.
C
C     IFAIL - THE USUAL FAILURE PARAMETER. IF IN DOUBT SET
C             IFAIL TO ZERO BEFORE CALLING F02WAX.
C
C     OUTPUT PARAMETERS.
C
C     A     - THE TOP N*N PART OF A WILL CONTAIN THE N*N ORTHOGONAL
C             MATRIX P**T.
C             THE REMAINING (M-N)*N PART OF A IS USED FOR INTERNAL
C             WORKSPACE.
C
C     B     - IF WANTB IS .TRUE. THEN B IS OVERWRITTEN BY
C             THE M ELEMENT VECTOR (Q**T)*B.
C
C     SV    - N ELEMENT VECTOR CONTAINING THE SINGULAR
C             VALUES OF A. THEY ARE ORDERED SO THAT
C             SV(1).GE.SV(2).GE. ... .GE.SV(N).GE.0.
C
C     IFAIL - ON NORMAL RETURN IFAIL WILL BE ZERO.
C             IN THE UNLIKELY EVENT THAT THE QR-ALGORITHM
C             FAILS TO FIND THE SINGULAR VALUES IN 50*N
C             ITERATIONS THEN IFAIL IS SET TO 2.
C             IF AN INPUT PARAMETER IS INCORRECTLY SUPPLIED
C             THEN IFAIL IS SET TO UNITY.
C
C     WORKSPACE PARAMETERS.
C
C     WORK  - A 3*N ELEMENT VECTOR.
C             WORK(1) RETURNS THE TOTAL NUMBER OF ITERATIONS TAKEN
C             BY THE QR-ALGORITHM.
C
C     LWORK - THE LENGTH OF THE VECTOR WORK. LWORK MUST BE
C             AT LEAST 3*N.
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='F02WAX')
C     .. Scalar Arguments ..
      INTEGER           IFAIL, LWORK, M, N, NRA
      LOGICAL           WANTB
C     .. Array Arguments ..
      DOUBLE PRECISION  A(NRA,N), B(M), SV(N), WORK(LWORK)
C     .. Local Scalars ..
      INTEGER           IERR, NP1, NPNP1
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          F01LZF, F01QCF, F02SZF, F02WAY, F01QDF
C     .. Executable Statements ..
      IERR = IFAIL
      IF (IERR.EQ.0) IFAIL = 1
C
      IF (NRA.LT.M .OR. M.LT.N .OR. LWORK.LT.3*N .OR. N.LT.1)
     *    GO TO 20
C
      NP1 = N + 1
      NPNP1 = N + NP1
C
C     Call to F01QAF replaced by a call to F01QCF.
C     CALL F01QAF(M,N,A,NRA,A,NRA,WORK,IFAIL)
      CALL F01QCF(M,N,A,NRA,WORK,IFAIL)
C
C     Call to F02WAZ replaced by a call to F01QDF.
C     IF (WANTB) CALL F02WAZ(M,N,A,NRA,WORK,B,B)
      IF (WANTB) CALL F01QDF('Transpose','Separate',M,N,A,NRA,WORK,1,B,
     *                       M,WORK(N+1),IFAIL)
C
      CALL F01LZF(N,A,NRA,A,NRA,WANTB,B,.FALSE.,.FALSE.,WORK,1,1,
     *            .FALSE.,WORK,1,1,SV,WORK,WORK,WORK,IFAIL)
C
      CALL F02WAY(N,A,NRA,A,NRA)
C
      IFAIL = 1
      CALL F02SZF(N,SV,WORK,SV,WANTB,B,.FALSE.,WORK,1,1,.TRUE.,A,NRA,N,
     *            WORK,WORK(NP1),WORK(NPNP1),IFAIL)
C
      IF (IFAIL.EQ.0) RETURN
C
      IFAIL = 2
   20 IFAIL = P01ABF(IERR,IFAIL,SRNAME,0,P01REC)
      RETURN
      END
