      LOGICAL FUNCTION F04JGX(A,B,SMALL)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (OVFLOW)
C
C     F04JGX WILL BE .TRUE. IF THE DIVISION A/B IS LIKELY TO
C     RESULT IN OVERFLOW. F04JGX WILL BE .FALSE. IF A/B CAN BE
C     COMPUTED WITHOUT OVERFLOW.
C
C     SMALL MUST BE THE SMALL POSITIVE REAL NUMBER RETURNED
C     FROM ROUTINE X02AMF.
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION        A, B, SMALL
C     .. Intrinsic Functions ..
      INTRINSIC               ABS
C     .. Executable Statements ..
      IF (B.EQ.0.0D0) GO TO 20
      F04JGX = .FALSE.
      IF (ABS(B).GE.1.0D0) RETURN
      IF (ABS(A).LE.ABS(B)/SMALL) RETURN
   20 F04JGX = .TRUE.
      RETURN
      END
