      SUBROUTINE E02AKY(XMIN,XMAX,X,XCAP)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     * * * * * * * * * * * * * * * * * * * * * * * * * * *
C
C     NPL DATA FITTING LIBRARY ROUTINE NRMLZE
C
C     CREATED 5/5/78    UPDATED 11/12/78    RELEASE NO. 00/02.
C
C     AUTHORS.. GERALD T ANTHONY, MAURICE G COX, BETTY CURTIS
C     AND J GEOFFREY HAYES.
C     NATIONAL PHYSICAL LABORATORY
C     TEDDINGTON, MIDDLESEX, ENGLAND.
C
C     * * * * * * * * * * * * * * * * * * * * * * * * * * *
C
C     INPUT PARAMETERS
C        XMIN     MINIMUM VALUE OF X
C        XMAX     MAXIMUM VALUE OF X
C        X        UNNORMALIZED ARGUMENT IN RANGE (XMIN, XMAX)
C
C     OUTPUT PARAMETER
C        XCAP     NORMALIZED VALUE OF X
C
C     A VALUE OF X IS GIVEN, SUCH THAT
C     XMIN .LE. X .LE. XMAX.
C     XCAP IS CALCULATED SO THAT -1 .LE. X .LE. +1.
C
C     THIS FORM FOR XCAP ENSURES THAT THE COMPUTED VALUE HAS A
C     VERY SMALL ABSOLUTE ERROR.
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION  X, XCAP, XMAX, XMIN
C     .. Executable Statements ..
      XCAP = ((X-XMIN)-(XMAX-X))/(XMAX-XMIN)
      RETURN
C
C     END E02AKY
C
      END
