      SUBROUTINE E02DFZ(NXORDR,NXKNTS,XMIN,XMAX,XLAM,LXLAM,NYORDR,
     *                  NYKNTS,YMIN,YMAX,YLAM,LYLAM,C,IC1,IC2,LC,MX,X,
     *                  MY,Y,S,IS1,IS2,LS,WRK,LWRK,IWRK,LIWRK)
C     MARK 14 RELEASE. NAG COPYRIGHT 1989.
C     A modified DASL routine. The length of the real workspace
C     required has been reduced by 2*max(NXORDR,NYORDR) elements,
C     because space is no longer required in E02DFY for copying
C     of knots.
C
C     **********************************************************
C
C     D A S L  -  DATA APPROXIMATION SUBROUTINE LIBRARY
C
C     SUBROUTINE B2VR      BIVARIATE POLYNOMIAL SPLINE
C     ===============      EVALUATION ON RECTANGULAR MESH
C                          - BASE (WORKSPACE ALLOCATION)
C                          VERSION
C
C     CREATED 23 07 80.  UPDATED 25 11 82.  RELEASE 00/12
C
C     AUTHORS ... MAURICE G. COX AND PAULINE E. M. CURTIS.
C     NATIONAL PHYSICAL LABORATORY, TEDDINGTON,
C     MIDDLESEX TW11 OLW, ENGLAND.
C
C     (C)  CROWN COPYRIGHT 1980-1982
C
C     **********************************************************
C
C     E02DFZ.  AN ALGORITHM FOR EVALUATING A BIVARIATE
C     POLYNOMIAL SPLINE  S(X, Y)  FROM ITS B-SPLINE
C     REPRESENTATION AT ALL VERTICES OF A RECTANGULAR MESH.
C
C     THE ROUTINE IS DESIGNED TO BE FAST, BUT THIS IS AT THE
C     EXPENSE OF SOME WORKSPACE.  IF SPEED IS LESS IMPORTANT
C     THAN SPACE,  E02DFZ  MAY BE CALLED SEVERAL TIMES WITH
C     ONE MESHLINE OF VALUES, FOR EXAMPLE, ON EACH CALL.
C
C     INPUT PARAMETERS
C        NXORDR   ORDER (DEGREE + 1) OF SPLINE  S  IN  X
C        NXKNTS   NUMBER OF INTERIOR AND EXTERIOR X-KNOTS
C        XMIN,
C        XMAX     LOWER AND UPPER ENDPOINTS OF  X-INTERVAL
C        XLAM     INTERIOR AND EXTERIOR X-KNOTS
C        LXLAM    DIMENSION OF  XLAM
C        NYORDR   ORDER (DEGREE + 1) OF SPLINE  S  IN  Y
C        NYKNTS   NUMBER OF INTERIOR AND EXTERIOR Y-KNOTS
C        YMIN,
C        YMAX     LOWER AND UPPER ENDPOINTS OF  Y-INTERVAL
C        YLAM     INTERIOR AND EXTERIOR Y-KNOTS
C        LYLAM    DIMENSION OF YLAM
C        C        B-SPLINE COEFFICIENTS OF  S
C        IC1,
C        IC2      INDEX INCREMENTS OF  C
C        LC       DIMENSION OF  C
C        MX       NUMBER OF  X-MESHLINES
C        X        X-MESHLINE VALUES
C        MY       NUMBER OF  Y-MESHLINES
C        Y        Y-MESHLINE VALUES
C
C     OUTPUT (AND ASSOCIATED DIMENSION) PARAMETERS
C        S        VALUES OF SPLINE
C        IS1,
C        IS2      INDEX INCREMENTS OF  S
C        LS       DIMENSION OF  S
C
C     WORKSPACE (AND ASSOCIATED DIMENSION) PARAMETERS
C        WRK      REAL WORKSPACE
C        LWRK     DIMENSION OF  WRK.
C                    .GE. NYORDR*(MY + 1) + NYKNTS + NXORDR
C        IWRK     INTEGER WORKSPACE
C        LIWRK    DIMENSION OF  IWRK.
C                   .GE. MY + NYKNTS + NYORDR.
C
C     .. Scalar Arguments ..
      DOUBLE PRECISION  XMAX, XMIN, YMAX, YMIN
      INTEGER           IC1, IC2, IS1, IS2, LC, LIWRK, LS, LWRK, LXLAM,
     *                  LYLAM, MX, MY, NXKNTS, NXORDR, NYKNTS, NYORDR
C     .. Array Arguments ..
      DOUBLE PRECISION  C(LC), S(LS), WRK(LWRK), X(MX), XLAM(LXLAM),
     *                  Y(MY), YLAM(LYLAM)
      INTEGER           IWRK(LIWRK)
C     .. Local Scalars ..
      INTEGER           IXBAS, IYBAS, IYBSI, IYDEP, IYINT, QY
C     .. External Subroutines ..
      EXTERNAL          E02DFY
C     .. Executable Statements ..
C
C     WORKSPACE ALLOCATION FOR  E02DFY
C
      QY = NYKNTS + NYORDR
      IYBAS = 1
      IXBAS = IYBAS + MY*NYORDR
      IYDEP = IXBAS + NXORDR
      IYINT = 1
      IYBSI = IYINT + MY
C
C     EVALUATE  S(X, Y)  AT THE REQUIRED POINTS
C
      CALL E02DFY(NXORDR,NXKNTS,XMIN,XMAX,XLAM,LXLAM,NYORDR,NYKNTS,YMIN,
     *            YMAX,YLAM,LYLAM,C,IC1,IC2,LC,MX,X,MY,Y,S,IS1,IS2,LS,
     *            WRK(IYBAS),MY*NYORDR,WRK(IXBAS),WRK(IYDEP),QY,
     *            IWRK(IYINT),IWRK(IYBSI),QY)
      RETURN
C
C     END E02DFZ
C
      END
