      SUBROUTINE E04KDF(N,SFUN,MONIT,IPRINT,MAXFUN,ETA,XTOL,DELTA,
     *                  STEPMX,IBOUND,BL,BU,X,HESL,LH,HESD,ISTATE,F,G,
     *                  IW,LIW,W,LW,IFAIL)
C
C     MARK 6 RELEASE NAG COPYRIGHT 1977
C     MARK 6A REVISED  IER-100
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     **************************************************************
C
C     E04KDF IS A COMPREHENSIVE MODIFIED NEWTON ALGORITHM FOR
C     FINDING
C     - AN UNCONSTRAINED MINIMUM OF A FUNCTION OF SEVERAL VARIABLES
C     - A MINIMUM OF A FUNCTION OF SEVERAL VARIABLES SUBJECT TO
C     FIXED UPPER AND/OR LOWER BOUNDS ON THE VARIABLES.
C     FIRST DERIVATIVES ARE REQUIRED.
C
C     THE ROUTINE IS ESSENTIALLY IDENTICAL TO THE SUBROUTINE BCMNAF
C     IN THE NPL ALGORITHMS LIBRARY (REF. NO. E4/32/F). IT CALLS
C     E04LBR WITH E04KDZ AS THE PARAMETER SHESS AND E04LBS (WHICH
C     CALLS E04BBZ) AS THE PARAMETER MINLIN.
C
C     THE USER MUST SUPPLY AN INITIAL APPROXIMATION TO THE MINIMUM
C     AND A SUBROUTINE SFUN TO COMPUTE THE FUNCTION VALUE AND/OR
C     GRADIENT VECTOR. (NOTE THAT FOR CONSISTENCY WITH OTHER E04
C     DOCUMENTATION, THE NAME FUNCT IS USED INSTEAD OF SFUN IN THE
C     WRITE-UP.) THE ARRAYS W AND IW ARE USED AS WORK-SPACE BY
C     E04LBR AND MUST BE DIMENSIONED AT LEAST MAX(8, 7*N + N(N-1)/2
C     ) AND 2, RESPECTIVELY. ON EXIT, E04KDF GIVES THE ESTIMATED
C     POSITION OF THE CONSTRAINED MINIMUM IN X AND THE LOWEST
C     FUNCTION VALUE IN F.
C
C     THE MAJORITY OF THE ARITHMETIC IS PERFORMED BY F01BQZ, F01DEF
C     AND F04AQZ, WHICH ARE CALLED MANY TIMES DURING THE SOLUTION OF
C     A PROBLEM. IMPLEMENTORS CAN REDUCE THE TIME TAKEN BY E04KDF
C     (PARTICULARLY WHEN N IS LARGE) BY PUTTING THE BODIES OF THESE
C     ROUTINES INTO MACHINE CODE.
C
C     PHILIP E. GILL, WALTER MURRAY, SUSAN M. PICKEN, MARGARET H.
C     WRIGHT AND ENID M. R. LONG, D.N.A.C., NATIONAL PHYSICAL
C     LABORATORY, ENGLAND
C
C     **************************************************************
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='E04KDF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  DELTA, ETA, F, STEPMX, XTOL
      INTEGER           IBOUND, IFAIL, IPRINT, LH, LIW, LW, MAXFUN, N
C     .. Array Arguments ..
      DOUBLE PRECISION  BL(N), BU(N), G(N), HESD(N), HESL(LH), W(LW),
     *                  X(N)
      INTEGER           ISTATE(N), IW(LIW)
C     .. Subroutine Arguments ..
      EXTERNAL          MONIT, SFUN
C     .. Local Scalars ..
      INTEGER           J, NH, NWHY
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          E04KDZ, E04LBR, E04LBS
C     .. Executable Statements ..
      NWHY = 1
C
C     REMAINING INPUT VALUES WILL BE CHECKED BY E04LBR
C
      NH = N*(N-1)/2
      IF (NH.EQ.0) NH = 1
      DO 20 J = 1, NH
         HESL(J) = 0.0D0
   20 CONTINUE
      DO 40 J = 1, N
         HESD(J) = 0.0D0
   40 CONTINUE
      CALL E04LBR(N,SFUN,E04KDZ,.FALSE.,MONIT,IPRINT,E04LBS,MAXFUN,ETA,
     *            XTOL,DELTA,STEPMX,IBOUND,BL,BU,X,HESL,LH,HESD,ISTATE,
     *            F,G,IW,LIW,W,LW,NWHY)
      IF (NWHY.EQ.0) GO TO 80
   60 IFAIL = P01ABF(IFAIL,NWHY,SRNAME,0,P01REC)
      RETURN
   80 IFAIL = 0
      RETURN
C
C     END OF E04KDF (BCMNAF)
C
      END
