      SUBROUTINE E04LBF(N,SFUN,SHESS,MONIT,IPRINT,MAXFUN,ETA,XTOL,
     *                  STEPMX,IBOUND,BL,BU,X,HESL,LH,HESD,ISTATE,F,G,
     *                  IW,LIW,W,LW,IFAIL)
C
C     MARK 6 RELEASE NAG COPYRIGHT 1977
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     **************************************************************
C
C     E04LBF IS A COMPREHENSIVE MODIFIED NEWTON ALGORITHM FOR
C     FINDING
C     - AN UNCONSTRAINED MINIMUM OF A FUNCTION OF SEVERAL VARIABLES
C     - A MINIMUM OF A FUNCTION OF SEVERAL VARIABLES SUBJECT TO
C     FIXED UPPER AND/OR LOWER BOUNDS ON THE VARIABLES.
C     FIRST AND SECOND DERIVATIVES ARE REQUIRED.
C
C     THE ROUTINE IS ESSENTIALLY IDENTICAL TO THE SUBROUTINE BCMNA
C     IN THE NPL ALGORITHMS LIBRARY (REF. NO. E4/31/F). IT CALLS
C     E04LBR WITH E04LBS (WHICH CALLS E04BBZ) AS THE PARAMETER
C     MINLIN.
C
C     THE USER MUST SUPPLY AN INITIAL APPROXIMATION TO THE MINIMUM,
C     A SUBROUTINE SFUN TO COMPUTE THE FUNCTION VALUE AND/OR
C     GRADIENT VECTOR, AND A SUBROUTINE SHESS TO CALCULATE THE
C     HESSIAN MATRIX. (NOTE THAT, FOR CONSISTENCY WITH OTHER E04
C     DOCUMENTATION, THE NAMES FUNCT AND HESS ARE USED INSTEAD OF
C     SFUN AND SHESS IN THE WRITE-UP.) THE ARRAYS W AND IW ARE USED
C     AS WORK-SPACE BY E04LBR AND MUST BE DIMENSIONED AT LEAST
C     MAX(8, 7*N + N(N-1)/2 ) AND 2, RESPECTIVELY. ON EXIT, E04LBF
C     GIVES THE ESTIMATED POSITION OF THE CONSTRAINED MINIMUM IN X
C     AND THE LOWEST FUNCTION VALUE IN F.
C
C     THE MAJORITY OF THE ARITHMETIC IS PERFORMED BY F01BQZ, F01DEF
C     AND F04AQZ, WHICH ARE CALLED MANY TIMES DURING THE SOLUTION OF
C     A PROBLEM. IMPLEMENTORS CAN REDUCE THE TIME TAKEN BY E04LBF
C     (PARTICULARLY WHEN N IS LARGE) BY PUTTING THE BODIES OF THESE
C     ROUTINES INTO MACHINE CODE.
C
C     PHILIP E. GILL, WALTER MURRAY, SUSAN M. PICKEN, MARGARET H.
C     WRIGHT AND ENID M. R. LONG, D.N.A.C., NATIONAL PHYSICAL
C     LABORATORY, ENGLAND
C
C     **************************************************************
C
C     .. Parameters ..
      CHARACTER*6       SRNAME
      PARAMETER         (SRNAME='E04LBF')
C     .. Scalar Arguments ..
      DOUBLE PRECISION  ETA, F, STEPMX, XTOL
      INTEGER           IBOUND, IFAIL, IPRINT, LH, LIW, LW, MAXFUN, N
C     .. Array Arguments ..
      DOUBLE PRECISION  BL(N), BU(N), G(N), HESD(N), HESL(LH), W(LW),
     *                  X(N)
      INTEGER           ISTATE(N), IW(LIW)
C     .. Subroutine Arguments ..
      EXTERNAL          MONIT, SFUN, SHESS
C     .. Local Scalars ..
      INTEGER           NWHY
C     .. Local Arrays ..
      CHARACTER*1       P01REC(1)
C     .. External Functions ..
      INTEGER           P01ABF
      EXTERNAL          P01ABF
C     .. External Subroutines ..
      EXTERNAL          E04LBR, E04LBS
C     .. Executable Statements ..
      NWHY = 1
C
C     REMAINING INPUT VALUES WILL BE CHECKED BY E04LBR
C
      CALL E04LBR(N,SFUN,SHESS,.TRUE.,MONIT,IPRINT,E04LBS,MAXFUN,ETA,
     *            XTOL,0.0D+0,STEPMX,IBOUND,BL,BU,X,HESL,LH,HESD,ISTATE,
     *            F,G,IW,LIW,W,LW,NWHY)
      IF (NWHY.EQ.0) GO TO 40
   20 IFAIL = P01ABF(IFAIL,NWHY,SRNAME,0,P01REC)
      RETURN
   40 IFAIL = 0
      RETURN
C
C     END OF E04LBF (BCMNA)
C
      END
