      SUBROUTINE E04VDM(MODE,NCNLN,N,NROWJ,X,C,CJAC,NSTATE)
C     MARK 11 RELEASE. NAG COPYRIGHT 1983.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C
C     E04VDM IS A DUMMY CONFUN ROUTINE FOR USE WITH E04VDF AND E04VCF.
C
C     .. Scalar Arguments ..
      INTEGER           MODE, N, NCNLN, NROWJ, NSTATE
C     .. Array Arguments ..
      DOUBLE PRECISION  C(NROWJ), CJAC(NROWJ,N), X(N)
C     .. Executable Statements ..
      RETURN
C
C     END OF E04VDM. ( CONFUN. )
C
      END
